#!/usr/bin/env sh

# This is the first file ran on xinit, apparently.
# In a LARBS fashion, to be compatible with display managers, this file only
# does what a display manager would do - source ~/.xprofile if it exists and
# load the window manager.

printf >&2 "Display: %s\n" "${DISPLAY}"

# source xprofile
if [ -f "$XDG_CONFIG_HOME/xorg/xprofile" ]; then
  . "$XDG_CONFIG_HOME/xorg/xprofile"
elif [ -f ~/.xprofile ]; then
  . ~/.xprofile
fi

case "$WM" in
  i3|bspwm|dwm|qtile|awesome) ;;
  *) printf >&2 'WARNING: window manager "%s" is not yet supported - it might fail terribly.\n' "$WM" ;;
esac

exec "$WM"
