#!/usr/bin/env sh

# This is the first file ran on xinit, apparently.
# In a LARBS fashion, to be compatible with display managers, this file only
# does what a display manager would do - source ~/.xprofile if it exists and
# load the window manager.

printf >&2 "Display: %s\n" "$DISPLAY"
printf >&2 "Session folder: $XSESSION"

# helps when, for example
# if debugging dwm, opening the xserver with WM=./dwm
wm_raw="$WM"
export WM=$(basename "$WM")

xprofile="$XDG_CONFIG_HOME/xorg/xprofile"
if [ ! -f "$xprofile" ]; then
  xprofile=~/.xprofile
fi

case "$WM" in
  pencil)
    # do nothing, but pencil should run the profile when it decides to
    ;;
  *) [ -f "$xprofile" ] && . "$xprofile" ;;
esac

case "$WM" in
  i3|bspwm|dwm|qtile|awesome|pencil) ;;
  *) printf >&2 'WARNING: window manager "%s" is not yet supported - this might cause problems.\n' "$WM" ;;
esac

wmLog="$XSESSIONDIR/wm"
exec "$wm_raw" 2>&1 >"$wmLog"
