#!/usr/bin/env sh

# This file is ran when starting an X server.

# Source xprofile,
[ -f ~/.xprofile ] && . ~/.xprofile

case "$WM" in
  i3) exec i3 ;;
  bspwm) exec bspwm ;;
  dwm) exec dwm ;;
  *)
    printf 'Window manager "%s" is not yet supported.\n' "$WM"
    exit 1
    ;;
esac
