#!/usr/bin/env sh

# This is the first file ran on xinit, apparently.
# In a LARBS fashion, to be compatible with display managers, this file only
# does what a display manager would do - source ~/.xprofile if it exists and
# load the window manager.

printf >&2 "Display: %s\n" "${DISPLAY}"

# source xprofile
if [ -f "$XDG_CONFIG_HOME/xorg/xprofile" ]; then
  . "$XDG_CONFIG_HOME/xorg/xprofile"
elif [ -f ~/.xprofile ]; then
  . ~/.xprofile
fi

case "$WM" in
  i3) exec i3 ;;
  bspwm) exec bspwm ;;
  dwm) exec dwm ;;
  *)
    printf &>2 'Window manager "%s" is not yet supported.\n' "$WM"
    exit 1
    ;;
esac
