#!/usr/bin/env sh

# This is the first file ran on xinit, apparently.
# In a LARBS fashion, to be compatible with display managers, this file only
# does what a display manager would do - source ~/.xprofile if it exists and
# load the window manager.

[ -f ~/.xprofile ] && . ~/.xprofile

case "$WM" in
  i3) exec i3 ;;
  bspwm) exec bspwm ;;
  dwm) exec dwm ;;
  *)
    printf &>2 'Window manager "%s" is not yet supported.\n' "$WM"
    exit 1
    ;;
esac
