#!/usr/bin/env sh
#
# A collection of commands to run on the start of an X session.
# This should be sourced by ~/.xinitrc or your display manager, and not simply
# loaded alone.

exists() { command -v "$1" >/dev/null 2>/dev/null; }

# xrandr --output HDMI1 --auto --right-of eDP1
gen-xres | xrdb # update xresources database
setbg &

# wm-specific config
case "$WM" in
  dwm)
    if exists rootblocks; then
      rootblocks &
    else
      dwmblocks &
      pactl subscribe | grep --line-buffered "sink" | xargs -I'{}' pkill -RTMIN+10 dwmblocks >/dev/null 2>/dev/null &
    fi
    ;;
  pencil)
    start-polybar &
    ;;
esac

if [ "$WM" = bspwm ]; then
  start-sxhkd standard bspwm
else
  start-sxhkd standard
fi &

# compositor
if [ "$WM" = dwm ]; then
  sleep 3 # tray patch causes problems with compositor for some reason
  start-compositor
else
  start-compositor
fi &

# screenshot app ~ pick one
# flameshot &
ksnip &

# other background applications
[ "$WM" != awesome ] && dunst -config "$XDG_CACHE_HOME/gen/dunstrc" & # notification daemon
# nm-applet & # network manager on tray - currently experimenting not using this
monitor-battery & # notify when battery is running low
# blueman-applet & # bluetooth manager on tray - currently experimenting not using this
fcitx -d & # input method for multilingual input
if exists pulse-autoconf; then
  pulse-autoconf & # nice pulseaudio assistant daemon
fi
xsettingsd & # X settings daemon

# extra config (async)
systemd-inhibit --what=handle-power-key sleep infinity & # disable power button

# TODO: find an even better way to make this portable
xinput set-prop "Synaptics TM3096-006" "libinput Tapping Enabled" 1 # Touchpad: tap to click (not working)
xinput set-prop "Synaptics TM3096-006" "libinput Natural Scrolling Enabled" 1 # Touchpad: natural scrolling
