#!/usr/bin/env sh

# A collection of commands to run on the start of an X session.
# This should be sourced by ~/.xinitrc or your display manager, and not simply
# loaded alone.

# reload environment variables
. ~/.config/dots/env.sh

# wm-specific config
case "$WM" in
  bspwm)
    # sxhkd is started in bspwmrc
    # setbg is started in bspwmrc
    ;;
  dwm)
    start-sxhkd standard &
    setbg &
    dwmblocks &
    ;;
  i3)
    start-sxhkd standard &
    setbg &
    ;;
esac

# background applications
picom -b & # compositor
dunst & # notification daemon
flameshot & # screenshot app
nm-applet & # network manager on tray
monitor-battery &
blueman-applet &

# extra config (async)
systemd-inhibit --what=handle-power-key sleep infinity & # disable power button

# extra config (not async)
setxkbmap -layout br # set keyboard layout
xset r rate 400 35 # speed up xrate
gen-xres | xrdb # update xresources database

# TODO: find an even better way to make this portable
xinput set-prop "Synaptics TM3096-006" "libinput Tapping Enabled" 1 # Touchpad: tap to click (not working)
xinput set-prop "Synaptics TM3096-006" "libinput Natural Scrolling Enabled" 1 # Touchpad: natural scrolling
