#!/usr/bin/env sh

# A collection of commands to run on the start of an X server.

# Environent variables
source ~/.local/share/env.sh
source ~/.local/lib/ystd.sh

# Daemons
picom -b & # Compositor
dunst & # Notification daemon
exists dropbox && dropbox start &
[ "$WM" != bspwm ] 
  && start-sxhkd standard & # sxhkd when not on bspwm

# Background apps
flameshot & # Screenshot app

# Applets
nm-applet & # Network manager on tray
blueman-applet & # Bluetooth

# Configuration
systemd-inhibit --what=handle-power-key sleep infinity & # Disable power button
xset r rate 400 35 & # Speed up xrate
xinput set-prop 16 325 1 & # Touchpad: tap to click
xinput set-prop 16 307 1 & # Touchpad: natural scrolling
setxkbmap -layout br & # Keyboard layout
xrdb ~/.Xresources

# Scripts
battery-check & # Battery check & etc.
