#!/usr/bin/env sh

# [Stolen from Lukesmithxyz/voidrice]
# Gives a dmenu prompt to mount unmounted drives and Android phones. If
# they're in /etc/fstab, they'll be mounted automatically. Otherwise, you'll
# be prompted to give a mountpoint from already existsing directories. If you
# input a novel directory, it will prompt you to create that directory.

getMount() {
  [ -z "$chosen" ] && exit 1
  mp="$(find "$@" 2>/dev/null | dmenu -i -p "Mount point:")"
  [ "$mp" = "" ] && exit 1
  if [ ! -d "$mp" ]; then
    mkdiryn=$(printf 'No\nYes' | dmenu -i -p "$mp does not exist. Create it?")
    [ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
  fi
}

mountUsb() {
  chosen="$(print "%s" "$usbDrives" | dmenu -i -p "Mount which drive?" | awk '{print $1}')"
  sudo -A mount "$chosen" 2>/dev/null && notify-send "USB mounting" "$chosen mounted." && exit 0
  alreadymounted=$(lsblk -nrpo "name,type,mountpoint" | awk '$2=="part"&&$3!~/\/boot|\/home$|SWAP/&&length($3)>1{printf "-not \\( -path *%s -prune \\) \\ \n",$3}')
  getMount /mnt /media /mount -maxdepth 5 -type d "$alreadymounted"
  partitiontype="$(lsblk -no "fstype" "$chosen")"
  case "$partitiontype" in
    "vfat") sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000;;
    *) sudo -A mount "$chosen" "$mp"; user="$(whoami)"; ug="$(groups | awk '{print $1}')"; sudo -A chown "$user":"$ug" "$mp";;
  esac
  notify-send "USB mounting" "$chosen mounted to $mp."
}

mountAndroid() {
  chosen=$(printf "%s" "$androidDrives" | dmenu -i -p "Which Android device?" | cut -d : -f 1)
  getMount "$HOME" -maxdepth 3 -type d
  simple-mtpfs --device "$chosen" "$mp"
  notify-send "Android Mounting" "Android device mounted to $mp."
}

asktype() { \
  case $(printf 'USB\nAndroid' | dmenu -i -p "Mount a USB drive or Android device?") in
    USB) mountUsb ;;
    Android) mountAndroid ;;
  esac
}

androidDrives=$(simple-mtpfs -l 2>/dev/null)
usbDrives="$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"

if [ -z "$usbDrives" ]; then
  if [ -z "$androidDrives" ]; then
    printf >&2 "%s" "No USB drive or Android device detected"
    exit 1
  fi
  mountAndroid
else
  if [ -z "$androidDrives" ]; then
    mountUsb
  else
    asktype
  fi
fi
