#!/usr/bin/env bash

NVIM_PLUGS_FOLDER="${NVIM_PLUGS_FOLDER:-"$HOME/.cache/neovim-plugins"}"

if [ ! -d "$NVIM_PLUGS_FOLDER" ]; then
  printf >&2 "%s\n" "Making neovim plugin directory..."
  mkdir -p "$NVIM_PLUGS_FOLDER"
fi

ip "ion-vim@yohanandiamond" "https://gitlab.redox-os.org/YohananDiamond/ion-vim"
ip "vim-toml" "https://github.com/cespare/vim-toml"
ip "vim-surround" "https://github.com/tpope/vim-surround"
ip "vim-repeat" "https://github.com/tpope/vim-repeat"
ip "vim-commentary" "https://github.com/tpope/vim-commentary"
ip "jsonc.vim" "https://github.com/neoclide/jsonc.vim"
# ip "lightline.vim" "https://github.com/itchyny/lightline.vim"
ip "yats.vim" "https://github.com/HerringtonDarkholme/yats.vim"
ip "emmet-vim" "https://github.com/mattn/emmet-vim"
ip "julia-vim" "https://github.com/JuliaEditorSupport/julia-vim"
ip "nvim-nim" "https://github.com/baabelfish/nvim-nim"
ip "tabular" "https://github.com/godlygeek/tabular"
ip "vim-markdown" "https://github.com/plasticboy/vim-markdown"
ip "gruvbox" "https://github.com/morhetz/gruvbox"
ip "vim-racket" "https://github.com/wlangstroth/vim-racket"
ip "vim-auto-popmenu" "https://github.com/skywind3000/vim-auto-popmenu"
ip "scribble.vim" "https://github.com/vim-scripts/scribble.vim"
ip "vim-python-pep8-indent" "https://github.com/Vimjas/vim-python-pep8-indent"
ip "pear-tree" "https://github.com/tmsvg/pear-tree"
ip "vim-buftabline" "https://github.com/ap/vim-buftabline"
ip "vim-vinegar" "https://github.com/tpope/vim-vinegar"
ip "haskell-vim" "https://github.com/neovimhaskell/haskell-vim"
ip "python-syntax" "https://github.com/vim-python/python-syntax"
ip "vim-rsi" "https://github.com/tpope/vim-rsi"
ip "dracula" "https://github.com/dracula/vim"
ip "vim-syntax-extra" "https://github.com/justinmk/vim-syntax-extra"
ip "base16-vim" "https://github.com/chriskempson/base16-vim"
ip "vim-lua-indent" "https://github.com/raymond-w-ko/vim-lua-indent"
ip "moonscript-vim" "https://github.com/leafo/moonscript-vim"
ip "rust.vim" "https://github.com/rust-lang/rust.vim"
# ip "AutoClose" "https://github.com/vim-scripts/AutoClose"
# ip "vim-lua-ftplugin" "https://github.com/xolox/vim-lua-ftplugin"
# ip "vim-lua" "https://github.com/tbastos/vim-lua"
# ip "vim-hy" "https://github.com/hylang/vim-hy"
# ip "vim-fsharp" "https://github.com/fsharp/vim-fsharp"
# ip "auto-pairs" "https://github.com/jiangmiao/auto-pairs"

# For NeoVim plugins
if [ -z "$NO_GC_NVIM_PLUGS" ]; then
  find "$NVIM_PLUGS_FOLDER" -mindepth 1 -maxdepth 1 |
    while read plug_path; do
      plug="$(basename "$plug_path")"
      if ! (grep -q "^$plug:.*\$" <<<"$ARR_NVIM_PLUGS" ||
              grep -q "^.*:$plug:.*\$" <<<"$ARR_NVIM_PLUGS" ||
              grep -q "^.*:$plug\$" <<<"$ARR_NVIM_PLUGS"); then
        if ! file "$plug_path" | grep -q "^$plug_path: symbolic link"; then
          printf >&2 "Removing disabled plugin [$plug]... "
          rm -rf "$plug_path" &&
            printf >&2 "done.\n" ||
            printf >&2 "failed.\n"
        fi
      fi
    done
fi
