#!/usr/bin/env sh

exists() { command -v "$1" >/dev/null 2>/dev/null; }

if [ -z "$ACR_WIKI_DIR" ]; then
  printf >&2 "ACR_WIKI_DIR not set - please set it\n"
  exit 1
fi

(
  cd "$ACR_WIKI_DIR"
  choice=$(fd -tf '\.(md|acr)$' | fzagnostic) || exit 1
  "$EDITOR" "$choice"
)
