#!/usr/bin/env python3

import sys

def help_and_exit():
    from pathlib import Path
    progname = Path(sys.argv[0]).name
    print("Usage: {progname} <PATH-OR-MODULE>")
    sys.exit(2)

def get_or_import(key: str):
    g = globals()
    return g[key] if key in g else __import__(key)

def main(args: list[str]) -> None:
    if len(args) != 2:
        help_and_exit()

    # TODO: make work on multiple-path modules (I think I need to __import__ the entire string and then do the getattr loop later)

    split1 = args[1].split(":")
    if len(split1) == 1:
        help(get_or_import(split1[0]))
    else:
        mod_name, var = split1

        x = get_or_import(mod_name)
        for value in var.split("."):
            x = getattr(x, value)
        help(x)

if __name__ == "__main__":
    main(sys.argv)
