# Enable wrap
add-highlighter global/ wrap
add-highlighter global/ number-lines

hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
}

hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

# Themes
colorscheme solarized-dark-termcolors

# Standard mappings
map global normal ç :
