# Highlighters
try %{
    add-highlighter global/ wrap
    add-highlighter global/ number-lines
}

hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
}

hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

# Commands
try %{
    define-command rl %{
        source ~/.config/kak/kakrc
    }
}

# Themes
colorscheme gruvbox
set-face global Default rgb:fbf1c7
set-face global LineNumbers rgb:7c6f64
set-face global BufferPadding rgb:7c6f64
set-face global StatusLine rgb:fbf1c7

# Standard mappings
map global normal ç :
