evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    if ! test -e "$plugins/plug.kak"; then
        git clone -q https://github.com/andreyorst/plug.kak "$plugins/plug.kak"
    fi

    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}

plug "andreyorst/plug.kak" noload

plug "andreyorst/smarttab.kak" config %{
    set-option global tabstop 8
    set-option global indentwidth 4

    hook global WinSetOption filetype=(.*) %{
        evaluate-commands %sh{
            case "$kak_opt_filetype" in
              makefile|gas) echo "noexpandtab" ;;
              c|cpp) echo "smarttab" ;;
              *) echo "expandtab" ;;
            esac

            echo "set-option global softtabstop $kak_opt_indentwidth"
        }
    }
}

plug "alexherbo2/auto-pairs.kak" config %{
    enable-auto-pairs
}

# Highlighters
add-highlighter global/ wrap
add-highlighter global/ number-lines -hlcursor
add-highlighter global/ regex \h+$ 0:Error

hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
}

hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

hook global WinSetOption filetype=nim %{
    set-option buffer indentwidth 2
}

hook global WinSetOption filetype=acrylic %{
    set-option buffer indentwidth 2
}

# Misc. mappings
map global normal -docstring "BR-ABNT2 convenience key" ç :
map global normal -docstring "leader mapping" <space> ,
map global normal -docstring "clear selection" , <space>
map global user -docstring "yank to clipboard" y "<a-|>xclip -i -sel clip<ret>"
map global user -docstring "paste from clipboard" p "!xclip -o -sel clip<ret>"
map global user -docstring "delete buffer" B ":db<ret>"

map global normal <c-j> ":buffer-next<ret>" # FIXME: doesn't work,,
map global normal <c-k> ":buffer-previous<ret>"

# TODO: https://github.com/mawww/kakoune/wiki/Selections
# TODO: https://github.com/mawww/kakoune/wiki/Selections-combinations
# TODO: https://stackoverflow.com/questions/44220509/how-do-i-select-multiple-lines-going-upwards-on-kakoune
# TODO: https://github.com/mawww/kakoune/issues/1285 -- select upwards
# TODO: https://github.com/mawww/kakoune/issues/2323 -- indentation guides

add-highlighter global/ regex \b(TODO|FIXME|XXX|NOTE)\b 0:default+rb

set-option global ui_options terminal_assistant=none

source "%val{config}/base16.kak"
source "%val{config}/rc/acrylic.kak"
