(deftheme term-dash
  "Yohanan's dashy terminal theme.")

(custom-theme-set-faces
 'term-dash
 '(default ((t (:background "black" :foreground "white"))))
 '(cursor ((((background light)) (:background "black")) (((background dark)) (:background "white")))))

;; (when (not (display-graphic-p))
;;   (custom-theme-set-faces 'term-dash
;;    '(default ((t (:inherit nil :stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
;;    '(fixed-pitch ((t (:family "Cascadia Code"))))
;;    '(variable-pitch ((t (:family "Sans Serif"))))
;;    '(escape-glyph ((t (:foreground "yellow"))))
;;    '(homoglyph ((t (:foreground "yellow"))))
;;    '(minibuffer-prompt ((t (:foreground "brightblue"))))
;;    '(highlight ((t (:background "magenta" :foreground "black"))))
;;    '(region ((t (:background "blue" :foreground "black"))))
;;    '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
;;    '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
;;    '(trailing-whitespace ((t (:background "red"))))
;;    '(font-lock-builtin-face ((t (:foreground "magenta"))))
;;    '(font-lock-comment-delimiter-face ((t (:inherit 'font-lock-comment-face nil))))
;;    '(font-lock-comment-face ((t (:foreground "color-245"))))
;;    '(font-lock-constant-face ((t (:foreground "color-214"))))
;;    '(font-lock-doc-face ((t (:foreground "green"))))
;;    '(font-lock-function-name-face ((t (:foreground "blue"))))
;;    '(font-lock-keyword-face ((t (:foreground "red"))))
;;    '(font-lock-negation-char-face ((t nil)))
;;    '(font-lock-preprocessor-face ((t (:foreground "magenta"))))
;;    '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
;;    '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
;;    '(font-lock-string-face ((t (:foreground "green"))))
;;    '(font-lock-type-face ((t (:foreground "yellow"))))
;;    '(font-lock-variable-name-face ((t (:foreground "white"))))
;;    '(font-lock-warning-face ((t (:background "red" :foreground "black"))))
;;    '(button ((t (:background "blue" :foreground "black"))))
;;    '(link ((t (:foreground "blue" :underline t))))
;;    '(link-visited ((t (:inherit link :foreground "magenta"))))
;;    '(fringe ((((class color) (background light)) (:background "grey95")) (((class color) (background dark)) (:background "grey10")) (t (:background "gray"))))
;;    '(header-line ((t (:underline (:color foreground-color :style line) :inverse-video nil :inherit (mode-line)))))
;;    '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
;;    '(mode-line ((t (:background "color-249" :foreground "black" :box (:line-width -1 :style released-button)))))
;;    '(mode-line-buffer-id ((t (:weight bold))))
;;    '(mode-line-emphasis ((t (:weight bold))))
;;    '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
;;    '(mode-line-inactive ((t (:inherit mode-line :background "black" :foreground "white" :box (:line-width -1 :color "grey40") :weight light))))
;;    '(isearch ((t (:background "yellow" :foreground "black"))))
;;    '(isearch-fail ((t (:background "red" :foreground "black"))))
;;    '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
;;    '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
;;    '(next-error ((t (:inherit (region)))))
;;    '(query-replace ((t (:background "color-240" :foreground "white"))))))

;; (provide-theme 'term-dash)
