if [ -z "$_INSIDE_TRUE_SHELL" ] && [ "$(uname -o)" = Android ] && [ "$SHELL" != "$0" ]; then
  # . ~/.config/dots/env.sh
  . ~/.config/dots/path.sh

  command "$SHELL" >/dev/null 2>/dev/null \
    && _INSIDE_TRUE_SHELL=1 exec "$SHELL"
fi

HISTFILE=~/.cache/bash_history
PS1='[\u@\h]\$ ' PS2='  '
