_STARTUP_DEBUG_TIME=$(date +"%s%3N")

. ~/.config/dots/env.sh

if [ -z "$_INSIDE_TRUE_SHELL" ] && [ "$(uname -o)" = Android ] && [ "$TERMUX_SHELL" != "$0" ]; then
  . ~/.config/dots/path.sh

  printf >&2 "Entering %s...\n" "$TERMUX_SHELL"

  command -v "$TERMUX_SHELL" >/dev/null 2>/dev/null \
    && SHELL="$TERMUX_SHELL" _INSIDE_TRUE_SHELL=1 exec "$TERMUX_SHELL"
fi

HISTFILE=~/.cache/bash_history
PS1='[\u@\h]\$ ' PS2='  '
