#!/usr/bin/env sh

. ~/.local/share/env.sh # reload environment variables

# desktop config
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# bspc config top_padding 0
# bspc config bottom_padding 0
# bspc config left_padding 0
# bspc config right_padding 0

bspc config window_gap 5 # with gaps
# bspc config window_gap 0 # without gaps

# other
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# border
bspc config border_width 1
bspc config focused_border_color '#8EC07C'
bspc config active_border_color '#32302F'
bspc config normal_border_color '#32302F'

# rules
bspc rule -a Zathura state=tiled
bspc rule -a Sxiv state=floating
bspc rule -a float state=floating

# kill some programs that probably were loaded in previous sessions
killall sxhkd

# programs to start along
start-sxhkd standard bspwm &
start-polybar &
setbg &
