#!/usr/bin/env sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config window_gap 7
bspc config top_padding 30
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config border_width 1
bspc config focused_border_color '#8EC07C'
bspc config active_border_color '#32302F'
bspc config normal_border_color '#32302F'

# bspc rule -a qutebrowser desktop='^2'
bspc rule -a Zathura state=tiled
bspc rule -a float state=floating
# bspc rule -a firefox desktop='^2'

killall sxhkd
start-sxhkd standard bspwm &
setbg &
start-polybar &
bspwm-events &
