# vim: ft=conf

reload-threads 16 # use many threads for refreshing
include /usr/share/doc/newsboat/contrib/colorschemes/nord

bind-key j down
bind-key k up
unbind-key J
unbind-key K
bind-key l open
bind-key h quit

bind-key g home
bind-key G end
bind-key s sort

# sure, cleaning up is fine but I'd rather do it manually (newsboat --cleanup)
cleanup-on-quit no
