#!/bin/sh

# This file is ran when starting an X server.
# [Partially stolen from Lukesmithxyz/voidrice]

# Source xprofile,
[ -f ~/.xprofile ] && . ~/.xprofile

case "${WM}" in
    i3)
        exec i3
        ;;
    *)
        echo "Window manager '${WM}': not yet supported."
        type i3 2>/dev/null >/dev/null &&
            i3 ||
            exit $?
        ;;
esac
