#!/bin/sh

# Commands to run on the start of the startup.

# Daemons & applets
picom -b & # Compositor
dunst & # Notification daemon
nm-applet & # Network manager on tray
sxhkd & # Simple X Hotkey Daemon

# Configuration
systemd-inhibit --what=handle-power-key sleep infinity & # Disable power button
xset r rate 400 35 & # Speed up xrate
xinput set-prop 16 325 1 & # Touchpad: tap to click
xinput set-prop 16 307 1 & # Touchpad: natural scrolling

# Scripts
setbg & # Set background
# TODO: recurring check
