scheme: "Catppuccin Frappe"
author: "https://github.com/catppuccin/catppuccin"
base00: "303446" # base
base01: "292c3c" # mantle
base02: "414559" # surface0
base03: "61677d" # surface1
base04: "727890" # surface2
base05: "c6d0f5" # text
base06: "f2d5cf" # rosewater
base07: "babbf1" # lavender
base08: "e78284" # red
base09: "ef9f76" # peach
base0A: "e5c890" # yellow
base0B: "a6d189" # green
base0C: "81c8be" # teal
base0D: "8caaee" # blue
base0E: "ca9ee6" # mauve
base0F: "eebebe" # flamingo
