#!/usr/bin/env sh

# This script shows info about arguments passed to it.
# It's useful for inspecting how word splitting works in your shell.

printf >&2 "Argument count: "
echo $#
echo >&2 "Arguments: "
while [ $# != 0 ]; do
  printf >&2 "  "
  printf "%s\n" "$1"
  shift
done
printf >&2 "[END]\n"
