#!/usr/bin/env sh

set -e
PROGNAME=$(basename "$0")

showHelp() {
  cat >&2 <<EOF
Usage: %s { load <FILE> | stop | reboot | monitor }
  load <FILE>: loads the specified uf2 file and resets the pico
  stop: stops the pico, putting it into bootsel mode
  reboot: restarts the current running program on the pico
  monitor: connects via serial to PICO_SERIAL_DEVICE (default /dev/ttyACM0)

Requirements for this to work:
  - picotool must be installed
  - if the program was compiled with pico-sdk via CMake:
    - pico_enable_stdio_usb is ON in CMakeLists.txt
    - stdio_init_all is called on the main function
EOF
  exit 2
}

[ $# = 0 ] && showHelp

case "$1" in
  load)
    [ $# = 2 ] || showHelp
    picotool load -uxf "$2"
    ;;
  stop)
    [ $# = 1 ] || showHelp
    picotool reboot -uf
    ;;
  reboot)
    [ $# = 1 ] || showHelp
    picotool reboot -f
    ;;
  monitor)
    [ $# = 1 ] || showHelp
    fd=${PICO_SERIAL_DEVICE:-/dev/ttyACM0}
    printf >&2 "Waiting for %s to be readable" "$fd"
    while [ ! -r "$fd" ]; do
      sleep 0.2
      printf >&2 "."
    done
    printf >&2 " - found!\n"
    picocom --echo "$fd"
    ;;
  *) showHelp ;;
esac
