#!/usr/bin/env sh

set -ue
progname=$(basename "$0")

isAndroid() { [ "${TERMUX_VERSION:-}" ]; }
exists() { command -v "$1" >/dev/null 2>/dev/null; }

showHelp() {
  cat >&2 <<EOF
Usage: $progname <PORT> <HOST> <USER> [COMMAND]
EOF
  exit 2
}

if [ $# -lt 3 ] || [ $# -gt 4 ]; then
  showHelp
fi

port=$1
host=$2
user=$3
cmd=${4:-}

# connect to GPG/SSH agent
if exists gpg-connect-agent && ! isAndroid; then
  gpg-connect-agent updatestartuptty /bye >/dev/null
fi

printf >&2 "Host: %s; user: %s\n" "$host" "$user"

if exists ping; then
  printf >&2 "Waiting host..."
  while true; do
    if ping -q -c1 "$host" >/dev/null 2>/dev/null; then
      break
    fi
    printf >&2 "."
  done
  printf >&2 " OK!\n"
fi

userSig="$user@$host"
exec ssh -t -p "$port" "$userSig" "$cmd"
