#!/usr/bin/env python

import subprocess as sp
import sys

# TODO: test for failure when calling the commands

def main() -> int:
    projects = {}

    p_tags = sp.run(["acr-get-tags"], stdout=sp.PIPE, encoding="utf-8")
    # assert p_tags.
    for line in p_tags.stdout.split("\n"):
        split = line.split(" ", maxsplit=1)

        id = split[0]
        if len(split) > 1:
            tags = split[1].split(" ")
        else:
            tags = []

        if "project" in tags:
            projects[id] = None

    p_titles = sp.run(["acr-list-titles"], stdout=sp.PIPE, encoding="utf-8")
    for line in p_titles.stdout.split("\n"):
        split = line.split(" ", maxsplit=1)
        id = split[0]
        if len(split) > 1:
            title = split[1]
        else:
            title = ""
        if id in projects:
            projects[id] = title

    for id, name in projects.items():
        print(id, name)

if __name__ == "__main__":
    sys.exit(main())
