#!/usr/bin/env sh

if [ -z "$ACW_WIKI_DIR" ]; then
  printf >&2 "ACW_WIKI_DIR not set - please set it\n"
  exit 1
fi

if exists nvim; then
  alias vim=nvim
elif exists vim; then
  true # do nothing
else
  printf >&2 "Could not find a suitable vim-compliant editor - do you have Vim or NeoVim?\n"
  exit 1
fi

cd "$ACW_WIKI_DIR"
choice=$(fd -tf '\.(md|wiki)$' | fzagnostic) || exit 1
vim "$choice"
