#!/usr/bin/env bash
#
# Shows info about arguments passed to it. Useful for inspecting how shells
# handle word splitting n stuff.
#
# Bashism: %q in printf

printf >&2 "Argument count: %s\n" $#
printf >&2 "Arguments:\n"
while [ $# != 0 ]; do
  printf >&2 "  "
  printf "%q\n" "$1"
  shift
done
