#!/usr/bin/env -S python3 -i
# vim: ft=python

import sys
import os
from math import *
from random import *
from pathlib import Path
from typing import Iterable

from operator import xor

def dcos(x: float) -> float: return cos(radians(x))
def dsin(x: float) -> float: return sin(radians(x))
def dtan(x: float) -> float: return tan(radians(x))

def res_ratio(x: int, y: int) -> tuple[int, int]:
    div = gcd(x, y)
    return (x // div, y // div)

def is_prime(p: int) -> bool:
    for i in range(2, p):
        if p % i == 0:
            return False
    return True

def factor(x: int) -> Iterable[int]:
    """This is probably bog slow btw."""

    factors = []

    def next_prime(p: int) -> int:
        p += 1
        while not is_prime(p):
            p += 1
        return p

    cur = x
    prime = next_prime(1)
    while cur > 1 and prime <= cur:
        while cur % prime == 0:
            factors.append(prime)
            cur //= prime
        prime = next_prime(prime)
    if cur != 1:
        raise Exception(f"Bad state: {cur=} {prime=} {factors=}")

    return factors
