#!/usr/bin/env sh

printf "    "
for col in $(seq 0 15); do
  printf "%3d" "$col"
done
printf " <- FG\n"

for line in $(seq 0 15); do
  printf "%3d " "$line"

  for col in $(seq 0 15); do
    printf "\033[48;5;%dm" "$line"
    printf "\033[38;5;%dm" "$col"
    printf "XXX"
    printf "\033[0m"
  done

  printf "\n"
done

printf "  ^\n BG\n"
