#!/usr/bin/env sh

set -ue
progname=$(basename "$0")

showHelp() {
  cat >&2 <<EOF
Usage: $progname [LINELEN]
Where LINELEN is the amount of numbers per line.
EOF
  exit 2
}

case $# in
  0) linelen=$(( $(tput cols) / 4 )) ;;
  1) linelen=$1 ;;
  2) showHelp ;;
esac

seq 0 255 | while read -r i; do
  printf '\033[38;5;%dm%03s\033[0m ' "$i" "$i"
  if [ $(( (i + 1) % linelen )) -eq 0 ]; then
    printf "\n"
  fi
done

printf "\n"
