#!/usr/bin/env sh

exists() { command -v "$1" >/dev/null 2>/dev/null; }

message() {
  if [ ! "$WAYLAND_DISPLAY" -a "$DISPLAY" ] && exists xtitle; then
    winTitle=$(xtitle)
  fi

  cpu=$(grep 'cpu ' /proc/stat | awk '{ usage=($2+$4)*100/($2+$4+$5) } END { print usage }')

  [ "$winTitle" ] && printf "%s\n\n" "$winTitle"
  date +"%Y/%m/%d %H:%M"

  printf "cpu %.0f%%\n" "$cpu"
  free -m | awk '
    NR==2 { printf "mem %.0f%%\n", $3*100/$2 }
    NR==3 { printf "swap %.0f%%\n", $3*100/$2 }
  '

  find /sys/class/power_supply/ | grep BAT | while read -r battery; do
    printf "bat %.0f%%" "$(cat "$battery/capacity")"
  done
  printf "%s\n" "$(dwmblocks-volume)"
}

if [ -t 2 ]; then
  printf >&2 "%s\n" "$(message 2>&1)"
else
  notify-send "$(message 2>&1)"
fi
