#!/usr/bin/env sh

message() {
  printf "[%s]\n" "$(xtitle)"
  printf "%s\n" "$(date +"%Y/%m/%d %H:%M")"
  printf "%s: %.0f%%\n" \
    "Battery" "$(cat /sys/class/power_supply/BAT0/capacity)" \
    "CPU" "$(grep 'cpu ' /proc/stat \
            | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')" \
    "RAM" "$(free -m \
            | awk 'NR==2{print $3*100/$2}')" \
    "Swap" "$(free -m \
            | awk 'NR==3{print $3*100/$2}')"
}

notify-send "$(message)"
