#!/usr/bin/env sh

[ $# = 2 ] || exit 2

pager=${PAGER:-less}

case "$1" in
  python) pydoc "$2" ;;
  linux) man 2 "$2" ;;
  c) man 3 "$2" ;;
  janet)
    validJanetSymbol() { printf "%s" "$1" | grep -q '[a-zA-Z0-9_\-\+\-\/\>\<]'; }
    if ! validJanetSymbol "$2"; then
      printf >&2 "error: invalid janet symbol: %s\n" "$2"
    fi
    janet -e "(doc $2)" | "$pager"
    ;;
  c++) cppman "$2" ;;
  *)
    printf >&2 "unknown backend %s\n" "$1"
    exit 2
    ;;
esac
