#!/usr/bin/env sh

set -ue
progname=$(basename "$0")

showHelp() {
  cat >&2 <<EOF
Usage: $progname <BACKEND> <QUERY>
BACKEND := { python | linux | c | janet | c++ | java | rust }
EOF
  exit 2
}

[ $# = 2 ] || showHelp

pager=${PAGER:-less}

case "$1" in
  python) pydoc "$2" ;;
  linux) man 2 "$2" ;;
  c) man 3 "$2" ;;
  janet)
    validJanetSymbol() { printf "%s" "$1" | grep -q '[a-zA-Z0-9_\-\+\-\/\>\<]'; }
    if ! validJanetSymbol "$2"; then
      printf >&2 "error: invalid janet symbol: %s\n" "$2"
    fi
    janet -e "(doc $2)" | "$pager"
    ;;
  c++) cppman "$2" ;;
  java)
    # this one is really bad but it's something
    javap -p "$2" | "$pager"
    ;;
  rust)
    # FIXME: this opens it on the browser.. :(
    rustup doc "$2"
    ;;
  *)
    printf >&2 "unknown backend %s\n" "$1"
    showHelp
    ;;
esac
