#!/usr/bin/env sh

. "$(uselib std)"

PROGNAME=$(basename $0)

showHelp() {
  printf >&2 "Usage: %s\n" "$PROGNAME <url> [output_file]"
  exit 1
}

case $# in
  1)
    [ "$1" = "-h" ] && showHelp
    url="$1" output="$(basename "$1" | sed 's/?.*$//g')"
    [ -t 1 ] || output="-" # send to stdout if on a pipe
    ;;
  2) url="$1" output="$2" ;;
  *)
    printf >&2 "%s: %s\n" "$PROGNAME" "invalid amount of arguments"
    showHelp
    ;;
esac

if [ "$output" != "-" ] && [ -e "$output" ]; then
  printf >&2 '%s: output file "%s" already exists\n' "$(basename $0)" "$output"
  exit 2
fi

if exists curl; then
  curl "$url" --output "$output" --retry 999 --retry-delay 0
elif exists wget; then
  wget "$url" -O "$output"
else
  printf >&2 "%s\n" "Neither curl nor wget was found. Please install them or implement support for them on this script."
fi
