#!/usr/bin/env sh
#
# Prints all batteries, their status and their percentage.

find /sys/class/power_supply | grep 'BAT' | while read -r battery; do
  capacity=$(cat "$battery/capacity")
  status=$(cat "$battery/status")

  case "$status" in
    [Dd]ischarging) status="bat" ;;
    [Nn]"ot charging") status="err" ;;
    [Cc]harging) status="chr" ;;
    [Uu]nknown) status="???" ;;
    [Ff]ull) status="max" ;;
    *) status="???" ;;
  esac

  printf "%s %s%% " "$status" "$capacity"
done
