#!/usr/bin/env sh

# line="$(amixer get Master | grep '[0-9]\{1,3\}%')"
# printf "vol "
# if [ "$(printf "%s" "$line" | awk '{print $6}')" = "[off]" ]; then
#   printf "OFF"
# else
#   printf "%s%%" "$(printf "%s" "$line" | awk '{print $3}')"
# fi

activeSink=$(pacmd list-sinks | awk '/* index:/ {print $3}')
line=$(
  pactl list sinks \
    | grep '^[[:space:]]Volume:' \
    | head -n 1 \
    | tail -n 1 \
    | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
)

printf "vol "
if [ "$(printf "%s" "$line")" = "[off]" ]; then
  printf "OFF"
else
  printf "%s%%" "$(printf "%s" "$line")"
fi
