#!/usr/bin/env sh

# FIXME: this only works with one sink... (it'll ignore anything other than the first sink, I believe)

# line="$(amixer get Master | grep '[0-9]\{1,3\}%')"
# printf "vol "
# if [ "$(printf "%s" "$line" | awk '{print $6}')" = "[off]" ]; then
#   printf "OFF"
# else
#   printf "%s%%" "$(printf "%s" "$line" | awk '{print $3}')"
# fi

muted=$(
  pactl list sinks \
    | grep '^[[:space:]]Mute:' \
    | head -n 1 \
    | tail -n 1 \
    | awk '{ print $2 }'
)

volume=$(
  pactl list sinks \
    | grep '^[[:space:]]Volume:' \
    | head -n 1 \
    | tail -n 1 \
    | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
)

if [ "$muted" = "no" ]; then
  printf "vol %s%%" "$volume"
else
  printf "vol OFF"
fi
