#!/usr/bin/env sh

# [Stolen from github.com/Lukesmithxyz/voidrice]
# A general, all-purpose extraction script.

# Default behavior: Extract archive into new directory
# Behavior with `-c` option: Extract contents into current directory

PROGNAME=$(basename "$0")

shelp() {
  printf >&2 "Usage: %s\n" "$PROGNAME [-c] ARCHIVE"
  printf >&2 "Options:\n"
  printf >&2 "  %s : %s\n" "-c" "Extract archive into current ditrectory rather than a new one."
  exit 1
}

[ $# = 0 ] && shelp

while getopts "hc" o; do
  case "$o" in
    c) extracthere="True" ;;
    *) shelp ;;
  esac
done

if [ -z "$extracthere" ]; then
  archive=$(readlink -f "$*") \
    && [ -f "$archive" ] \
    && directory=$(echo "$archive" | sed 's/\.[^\/.]*$//') \
    && mkdir -p "$directory" \
    && cd "$directory" || exit
else
  archive=$(readlink -f "$(echo "$*" | cut -d' ' -f2)")
fi

[ "$archive" = "" ] && printf "Give archive to extract as argument.\n" && exit

if [ -f "$archive" ]; then
  case "$archive" in
    *.tar.bz2|*.tbz2) tar -xvjf "$archive" ;;
    *.tar.xz) tar -xvf "$archive" ;;
    *.tar.gz|*.tgz) tar -xvzf "$archive" ;;
    *.lzma) unlzma "$archive" ;;
    *.bz2) bunzip2 "$archive" ;;
    *.rar) unrar x -ad "$archive" ;;
    *.gz) gunzip "$archive" ;;
    *.tar) tar -xvf "$archive" ;;
    *.zip) unzip "$archive" ;;
    *.Z) uncompress "$archive" ;;
    *.7z) 7z x "$archive" ;;
    *.xz) unxz "$archive" ;;
    *.exe) cabextract "$archive" ;;
    *) printf "extract: \"%s\" - unknown archive method\n" "$archive" ;;
  esac
else
  printf "File \"%s\" not found.\n" "$archive"
fi
