#!/usr/bin/env sh

. ~/.local/lib/ystd.sh
depCheck flameshot date

if [ $# != 1 ]; then
  printf >&2 "%s\n" "Usage: $(basename $0) { gui | full | fullc }"
  exit 1
fi

BASE_FOLDER="${FLAMEW_SCR_FOLDER:-$HOME/.cache/screenshots}"
folder="$BASE_FOLDER/$(date +%Y-%m)"

if ! mkdir -p "$folder"; then
  printf >&2 "%s\n" "Could not make directory $folder"
  exit 1
fi

case "$1" in
  "") flameshot gui -p "$folder" ;;
  gui) flameshot gui -p "$folder" ;;
  full) flameshot full -p "$folder" ;;
  fullc) flameshot full -c ;;
  *)
    printf >&2 "%s\n" "Invalid command."
    exit 1
    ;;
esac
