#!/usr/bin/env bash

set -ue
progname=$(basename "$0")

showHelp() {
  cat >&2 <<EOF
$progname: find a file on parent directories and do something with it.

Usage: $progname <FILE>
       { run-file | run-command }
       { current-dir | file-dir }
       <ARGS...>

Explanations:
  run-file: run the found file, with args ARGS; only works if it is executable.
  run-command: run the command (and args) ARGS after finding the file.
  current-dir: run the command/file on current directory
  file-dir: run the command/file on the script directory
EOF

  exit 2
}

[ $# -lt 4 ] && showHelp

# get args
file="$1"
actionType="$2"
actionDir="$3"
shift 3

# analyze args
case "$actionType" in
  run-file|run-command) ;;
  *) showHelp ;;
esac
case "$actionDir" in
  current-dir|file-dir) ;;
  *) showHelp ;;
esac

fileDir=$(upfind "$file")

case "$actionDir" in
  current-dir) ;;
  file-dir) cd "$fileDir" ;;
esac

case "$actionType" in
  run-file) "$fileDir/$file" "$@" ;;
  run-command) "$@" ;;
esac
