#!/usr/bin/env sh

# A script to find and load articles.
# Works better with fuzzy finders.

. ~/.local/lib/ystd.sh
depCheck fd

if [ $# != 0 ]; then
  printf >&2 "%s\n" "Usage: $(basename $0)"
  printf >&2 "%s %s\n" "The articles folder is" '${F_ARTICLES:-~/articles}'
  exit 1
fi

articles="${F_ARTICLES:-~/articles}"
if ! cd "$articles"; then
  printf >&2 "%s\n" "Couldn't open $articles"
  exit 1
fi

choice="$(fd -d 1 -t f '\.html$' | dmenu)" \
  && open "$choice"
