#!/usr/bin/env sh

. "$(uselib std)"
depCheck fd fzagnostic

if [ $# != 0 ]; then
  printf >&2 "Usage: %s\n" "$(basename $0)"
fi

genbk() {
  fd -d1 -td '.' ~
  fd -d1 -td '.' ~/pj/code

  [ -r "$DIR_BOOKMARKS" ] && sh "$DIR_BOOKMARKS"

  fd -d1 -td '.' ~/pj/etc &
  fd -d1 -td '.' ~/pj/clone &
  fd -d1 -td '.' ~/pj/write &
  [ -d "/run/media/$USER" ] && fd -d1 -td '.' "/run/media/$USER"

  wait $!
}

dopackHome() { sed "s|^$HOME|~|g"; }
unpackHome() { sed "s|^~|$HOME|g"; }

genbk | dopackHome | fzagnostic | unpackHome || exit 1
