#!/usr/bin/env sh

set -ue
progname=$(basename "$0")

showHelp() {
  cat >&2 <<EOF
Usage: $progname
EOF
  exit 2
}

[ $# = 0 ] || showHelp

genbk() {
  fd -d1 -td '.' ~
  fd -d1 -td '.' ~/pj/code

  if localPath=$(d.localconf get localpath 2>/dev/null); then
    rcPath="$localPath/share/bookmarks.sh"
    [ -r "$rcPath" ] && sh "$rcPath"
  fi

  fd -d1 -td '.' ~/pj/etc &
  fd -d1 -td '.' ~/pj/clone &
  fd -d1 -td '.' ~/pj/write &
  [ -d "/run/media/$USER" ] && fd -d1 -td '.' "/run/media/$USER" &

  wait
}

packHome() { sed "s|^$HOME|~|g"; }
unpackHome() { sed "s|^~|$HOME|g"; }

genbk | packHome | fzagnostic | unpackHome || exit 1
