#!/usr/bin/env sh

. ~/.local/lib/ystd.sh
depCheck udisksctl

showHelp() {
  printf >&2 "Usage: %s\n" "$(basename $0) { -m | -u }"
  printf >&2 "Options:\n"
  printf >&2 "    -m    mount\n"
  printf >&2 "    -u    unmount\n"
  exit 1
}

case $# in
  1)
    case "$1" in
      -m) mount=1 ;;
      -u) ;;
      *) showHelp ;;
    esac
    ;;
  *) showHelp ;;
esac

if [ "$mount" ]; then
  # mounting
  drives=$(lsblk -rpo "name,type,size,mountpoint" | awk '$2 == "part" && $4 == "" {printf "%s (%s)\n", $1, $3}')
  choice=$(printf "%s" "$drives" | fzagnostic -p "Mount:" | awk '{print $1}')
  if [ "$choice" ]; then
    udisksctl mount -b "$choice"
  else
    printf >&2 "Mount operation cancelled.\n"
  fi
else
  # unmounting
  drives=$(lsblk -rpo "name,type,size,mountpoint" | awk '$2 == "part" && $4 ~ /^\/run\/media\// {printf "%s (%s)\n", $1, $3}')
  choice=$(printf "%s" "$drives" | fzagnostic -p "Unmount:" | awk '{print $1}')
  if [ "$choice" ]; then
    udisksctl unmount -b "$choice"
  else
    printf >&2 "Unmount operation cancelled.\n"
  fi
fi
