#!/usr/bin/env bash
#
# A replacement for passmenu that works with fzagnostic

set -ue
progname=$(basename "$0")

showHelp() {
  cat >&2 <<EOF
Usage: $progname <TYPE> [OUTPUT]
  TYPE := { normal | otp }
  OUTPUT := { stdout | copy }, defaults to stdout
EOF
  exit 2
}

case $# in
  1) passType="$1" showType="stdout" ;;
  2) passType="$1" showType="$2" ;;
  *) showHelp ;;
esac

args=()

case "$passType" in
  normal) args+=(show) ;;
  otp) args+=(otp) ;;
  *) showHelp ;;
esac

case "$showType" in
  stdout) ;;
  copy) args+=(-c) ;;
  *) showHelp ;;
esac

# force gpg to connect because issues
gpg-connect-agent updatestartuptty /bye >/dev/null

storeDir=${PASSWORD_STORE_DIR:-$HOME/.password-store}

filterChoices() {
  if [ "$passType" = otp ]; then
    grep 't\?otp'
  else
    cat
  fi
}

getChoices() {(
  cd "$storeDir"
  find -type f \
    | filterChoices \
    | sed 's|^\./||g; s|\.gpg$||g'
)}

choice=$(getChoices | fzagnostic -p "Entry:")
exec pass "${args[@]}" "$choice"
