#!/usr/bin/env bash
#
# A replacement for passmenu that works with fzagnostic

shopt -s nullglob globstar

showHelp() {
  printf >&2 "Usage: %s { copy | otp }\n" "$(basename "$0")"
  exit 1
}
[ $# != 1 ] && showHelp

case "$1" in
  copy|otp) action="$1" ;;
  *) showHelp ;;
esac

# force gpg to connect because issues
gpg-connect-agent updatestartuptty /bye >/dev/null

prefix=${PASSWORD_STORE_DIR-~/.password-store}
files=("$prefix"/**/*.gpg)
files=("${files[@]#"$prefix"/}")
files=("${files[@]%.gpg}")

choice=$(printf "%s\n" "${files[@]}" | fzagnostic -p "Entry:") || exit 1
[ "$choice" ] || exit 1

args=()
[ "$1" = copy ] && args=(show -c)
[ "$1" = otp ] && args=(otp -c)

pass "${args[@]}" "$choice" || exit 1
