#!/usr/bin/env sh
# vim: fdm=marker

# A simple script for power actions.
# If no args are specified, fzagnostic is opened.
# If an arg is provided, this script tries to choose said option.

# Settings
OPTIONS='lock\nexit\nsuspend\nhibernate\nreboot\nshutdown'

. ~/.local/lib/ystd.sh
depCheck fzagnostic systemctl betterlockscreen

fuzzyMatch() { printf "$OPTIONS" | fzagnostic -p "Power: "; }
matchArgs() { # {{{
  case $# in
    0) local choice="$(fuzzyMatch)"
      if [ -n "$choice" ]; then
        matchArgs "$choice"
      else
        showHelp
      fi ;;

    1) case "$1" in
        lock|exit|suspend|hibernate|reboot|shutdown) \
          eval "action_$1" ;;
        *) showHelp ;;
      esac ;;

    *) showHelp ;;
  esac
} # }}}
showHelp() { # {{{
  printf >&2 "%s %s\n" "Usage: $(basename $0)" \
    "[{lock | exit | suspend | hibernate | reboot | shutdown}]"
  printf >&2 "%s\n" "If no argument is specified, a fzagnostic pop-up is shown."
} # }}}

# Actions
action_lock() { # {{{
  betterlockscreen -l && [ "$WM" = dwm ] && pkill -RTMIN+1 dwmblocks
} # }}}
action_exit() { # {{{
  case "$WM" in
    i3) i3-msg exit ;;
    bspwm) bspc quit ;;
    dwm)
      printf >&2 "%s\n" "dwm has a specific key to be shut down - refer to your config.h file"
      exit 1
      ;;
    *)
      printf >&2 'Unknown wm "%s" - exiting will not work\n' "$WM"
      exit 1
      ;;
  esac
} # }}}
action_suspend() { # {{{
  action_lock &
  sleep 1
  systemctl suspend
} # }}}
action_hibernate() { # {{{
  printf >&2 "The hibernate action is currently unimplemented\n"
  exit 1
} # }}}
action_reboot() { # {{{
  systemctl reboot
} # }}}
action_shutdown() { # {{{
  systemctl poweroff
} # }}}

matchArgs "$@"
