#!/usr/bin/env sh

. "$(uselib std)"

if [ $# != 0 ]; then
  printf >&2 "Usage: %s\n" "$(basename $0)"
fi

THEME_FILES_PATH=~/.config/dots/themes
THEME_CFG_PATH=~/.local/share/dots/theme

msg() {
  _msg=$(printf "$@")
  printf >&2 "%s\n" "$_msg"
  notify-send -- "$_msg"
}

if [ -d "$THEME_FILES_PATH" ]; then
  choice=$(ls "$THEME_FILES_PATH" | sed 's/\.yaml$//g' | fzagnostic -p "Theme:") || exit 1
  mkdir -p "$(dirname THEME_CFG_PATH)" \
    && printf "%s" "$choice" > "$THEME_CFG_PATH" || exit 1

  if [ "$DISPLAY" ] && exists xrdb; then
    xdb-reload || msg "Failed to reload theme to %s."
    eval "$(load-base16-theme --noprefix)"
  elif isAndroid; then
    gen-config termux
    termux-reload-settings
  elif isTTY; then
    tty-loadcolors
  fi
else
  printf >&2 "Could not find the directory %s. Please create it and put there your theme files.\n" "$THEME_FILES_PATH"
  exit 1
fi
