#!/usr/bin/env sh

set -ue

exists() { command -v "$1" >/dev/null 2>/dev/null; }
getPath() { printf "%s" "$PATH" | tr ':' '\n'; }

generateFileList() {
  if exists stest; then
    getPath | xargs stest -flx
  else
    getPath | xargs -I{} find {} | xargs -I{} basename {}
  fi
}

generateFileList | sort -u
