#!/usr/bin/env sh

cacheDir="${XDG_CACHE_HOME:-$HOME/.cache}"
cacheFile="$cacheDir/pathbin"
mkdir -p "$cacheDir"

IFS=:
if stest -dqr -n "$cacheFile" $PATH; then
  stest -flx $PATH | sort -u | tee "$cacheFile"
else
  cat "$cacheFile"
fi

