#!/usr/bin/env sh

eval "$(load-base16-theme)"

cat >"$XDG_CACHE_HOME/gen/setcolorsrc" <<EOF
1$base01
2$base02
3$base03
4$base04
5$base05
6$base06
7$base07
8$base08
9$base09
10$base0A
11$base0B
12$base0C
13$base0D
14$base0E
15$base0F
EOF
