#!/usr/bin/env bash

set -e

. "$DOTFILES/config/dots/env.sh"
eval "$(load-base16-theme --export)"

progname=$(basename "$0")

MINIMUM=(wget)
T_ANDROID=(termux)
T_COMPUTER=(stalonetray dunst gtk3 foot niri)
# generated on demand: yambar waybar

main() {
  def_targets=(_init)

  _isAndroid \
    && def_targets+=("${T_ANDROID[@]}") \
    || def_targets+=("${T_COMPUTER[@]}")

  [ $# = 0 ] && sel_targets=("${def_targets[@]}")
  [ $# -gt 0 ] && sel_targets=(_init "$@")
  [ $# = 1 ] && [ "$1" = all ] && sel_targets=("${def_targets[@]}")

  for t in "${sel_targets[@]}"; do
    fn_name="_t_$t"
    if declare -f "$fn_name" >/dev/null; then
      printf >&2 "%s: running target %s\n" "$progname" "$t"
      eval "$fn_name"
    else
      printf >&2 "%s: could not find target %s; skipping\n" "$progname" "$t"
    fi
  done

  return 0
}

gen() {
  mkdir -p "$(dirname "$2")"
  pp <"$1" >"$2"
}

_t__init() {
  mkdir -p "$XDG_CACHE_HOME/gen"
}

_t_stalonetray() {
  gen "$DOTFILES/config/gen/stalonetrayrc" "$XDG_CACHE_HOME/gen/stalonetrayrc"
}

_t_dunst() {
  gen "$DOTFILES/config/gen/dunstrc" "$XDG_CACHE_HOME/gen/dunstrc"
}

_t_gtk3() {
  PP_PREFIX="#!!" gen "$DOTFILES/config/gen/gtk3rc" "$XDG_CONFIG_HOME/gtk-3.0/settings.ini"

  # for i in 2 3; do
  #   _ln_dir="$HOME/.themes/dummy"
  #   _flatcolor_dir="$HOME/.themes/FlatColor"

  #   gen "$DOTFILES/config/gen/gtk-flatcolor-${i}.0" "$_flatcolor_dir/colors${i}"
  #   [ ! -d "$_ln_dir" ] && ln -s "$_flatcolor_dir" "$_ln_dir"
  # done
}

_t_foot() {
  PP_PREFIX="#!!" gen "$DOTFILES/config/gen/foot.ini" "$XDG_CONFIG_HOME/foot/foot.ini"
}

_t_yambar() {
  PP_PREFIX="#!!" gen "$DOTFILES/config/gen/yambar.yml" \
    "$XDG_CONFIG_HOME/yambar/config.yml"
}

_t_waybar() {
  PP_PREFIX="/*!!" gen "$DOTFILES/config/gen/waybar-style.css" \
    "$XDG_CONFIG_HOME/waybar/style.css"
}

_t_wget() {
  [ "$WGETRC" ] && printf "hsts-file = %s" "$XDG_CACHE_HOME/wget-hsts" >"$WGETRC"
}

_t_niri() {
  mkdir -p "$XDG_CONFIG_HOME/niri"
  PP_PREFIX="//!!" gen "$DOTFILES/config/gen/niri-config.kdl" "$NIRI_CONFIG"
}

_t_termux() {
  [ -d ~/.termux ] || return
  gen "$DOTFILES/config/gen/termux-colors" ~/.termux/colors.properties
}

main "$@"
