#!/usr/bin/env bash
# vim: foldmethod=marker

# a bash file that outputs xresources based on some configurations.
# I made this because managing a raw xresources file is very annoying specially because the C
# preprocessor is annoying af.

. ~/.config/dots/env.sh

xset() { printf "%s: %s\n" "$1" "$2"; }

# set theme {{{
case "$CURRENT_THEME" in
  dracula)
    COL0='#282A36'
    COL1='#FF5555'
    COL2='#50FA7B'
    COL3='#F1FA8C'
    COL4='#BD93F9'
    COL5='#FF79C6'
    COL6='#8BE9FD'
    COL7='#BFBFBF'
    COL8='#4D4D4D'
    COL9='#FF6E67'
    COL10='#5AF78E'
    COL11='#F4F99D'
    COL12='#CAA9FA'
    COL13='#FF92D0'
    COL14='#9AEDFE'
    COL15='#F8F8F2'
    ;;

  gruvbox_dark)
    COL0='#282828'
    COL1='#CC241D'
    COL2='#98971A'
    COL3='#D79921'
    COL4='#458588'
    COL5='#B16286'
    COL6='#689D6A'
    COL7='#A89984'
    COL8='#928374'
    COL9='#FB4934'
    COL10='#B8BB26'
    COL11='#FABD2F'
    COL12='#83A598'
    COL13='#D3869B'
    COL14='#8EC07C'
    COL15='#EBDBB2'
    ;;

  gruvbox_dark2)
    COL0='#282828'
    COL1='#9D0006'
    COL2='#79740E'
    COL3='#B57614'
    COL4='#076678'
    COL5='#8F3F71'
    COL6='#427B58'
    COL7='#FBF1C7'
    COL8='#32302F'
    COL9='#FB4934'
    COL10='#B8BB26'
    COL11='#FABD2F'
    COL12='#83A598'
    COL13='#D3869B'
    COL14='#8EC07C'
    COL15='#FBF1C7'
    ;;

  gruvbox_light)
    COL0='#FBF1C7'
    COL1='#CC241D'
    COL2='#98971A'
    COL3='#D79921'
    COL4='#458588'
    COL5='#B16286'
    COL6='#689D6A'
    COL7='#7C6F64'
    COL8='#928374'
    COL9='#9D0006'
    COL10='#79740E'
    COL11='#B57614'
    COL12='#076678'
    COL13='#8F3F71'
    COL14='#427B58'
    COL15='#3C3836'
    ;;
esac # }}}

FONT="JetBrains Mono Medium:pixelsize=14.5:antialias=true:autohint=true;"
COL_CURSOR="$COL15"
COL_FG="$COL15"
COL_BG="$COL0"

# st
xset 'st.alpha' "0.9"
xset 'st.font' "$FONT"

# dmenu
xset 'dmenu.font' "$FONT"
xset 'dmenu.norm.bg' "$COL0"
xset 'dmenu.norm.fg' "$COL15"
xset 'dmenu.norm.hl.bg' "$COL0"
xset 'dmenu.norm.hl.fg' "$COL3"
xset 'dmenu.sel.bg' "$COL15"
xset 'dmenu.sel.fg' "$COL0"
xset 'dmenu.sel.hl.bg' "$COL3"
xset 'dmenu.sel.hl.fg' "$COL0"
xset 'dmenu.out.bg' "$COL15"
xset 'dmenu.out.fg' "$COL15"

# dwm
xset 'dwm.norm.bg' "$COL0"
xset 'dwm.norm.fg' "$COL15"
xset 'dwm.norm.border' "$COL0"
xset 'dwm.sel.bg' "$COL5"
xset 'dwm.sel.fg' "$COL0"
xset 'dwm.sel.border' "$COL15"

# qutebrowser
xset 'qutebrowser.border' "$COL_BG"
xset 'qutebrowser.selection' '#44475a'

# general
xset '*.background' "$COL_BG"
xset '*.foreground' "$COL_FG"
xset '*.cursorColor' "$COL_CURSOR"
xset '*.cursor-color' "$COL_CURSOR"

for n in {0..15}; do
  xset "*.color${n}" "$(eval 'echo $COL'"${n}")"
done
