#!/usr/bin/env bash

case $# in
  0) ;;
  1) cd "$1" || exit 1 ;;
  *)
    printf >&2 "%s\n" "Usage: $(basename $0) [repo]"
    printf >&2 "%s\n" "If [repo] is not specified, the current directory is used as it."
    exit 1
    ;;
esac

if git status -sb; then
  printf >&2 '\e[2 q'
  while [ -z "$EXIT" ]; do
    printf >&2 "Options: %s\n" "(d diff) (a add-and-commit) (p pull) (s push) (f fetch) (l log) (q quit)"
    printf >&2 "       > "
    read -n1 option
    printf >&2 "\n"
    case "$option" in
      d)
        git add .
        git diff HEAD
        ;;
      a) git add . && git commit ;;
      l) git log --all --oneline ;;
      p) git pull ;;
      s) git push ;;
      f) git fetch ;;
      q) EXIT=0 ;;
      "") ;;
      ) EXIT=0 ;;
      "") clear ;;
      *) printf 'Invalid option: "%s"\n' "$option" ;;
    esac
  done
  exit "$EXIT"
else
  exit 1
fi
