#!/usr/bin/env sh

set -ue

gitDir=$(upfind .git)
cd "$gitDir"

main() {
  commit=$(git log --oneline --follow --diff-filter=ACMRTUXB -- "$1" \
    | head -n1 | cut -d' ' -f1)
  git show "$commit":"$1"
}

case $# in
  0)
    file=$(git log --pretty=format: --name-only --diff-filter=A | sort -u | fzf)
    main "$file"
    ;;
  1) main "$1" ;;
  *) exit 2 ;;
esac
