#!/usr/bin/env sh

set -ue
progname=$(basename "$0")

showHelp() {
  cat >&2 <<EOF
"All-in-one" git script to do various things.
Usage: $progname <COMMMAND> [ARGS...] - available commands:
  restore-file <FILE>:
    restore the latest version of a file in the log
  fz-restore-file:
    fuzzy-menu version of restore-file - opens the contents on an editor
  changed-rank [COUNT]:
    show top COUNT changed files in the repo (defaults to 0)
  push-safe: a safer version of the push, which asks for an upstream if one is not set
  pull-cheap: only pulls the current branch (saves bandwidth!)
  gitk-local:
    show gitk with all local branches
EOF
  exit 2
}

[ $# != 0 ] || showHelp

restoreFile() {
  commit=$(git log --oneline --follow --diff-filter=ACMRTUXB -- "$1" \
    | head -n1 | cut -d' ' -f1)
  git show "$commit":"$1"
}

pullCheap() {
  # A simple 'git pull' may pull from other branches, and waste bandwidth.
  # So let's figure out where exactly we need to pull from.

  # First attempt is to figure out the upstream branch name.
  localBranch=$(git rev-parse --abbrev-ref HEAD)
  remoteBranch=$(git for-each-ref --format='%(upstream:short)' "$(git symbolic-ref -q HEAD)")
  remoteName=${remoteBranch%%/*}
  if [ "$remoteName" ]; then
    printf >&2 "Pulling branch \"%s\" from remote \"%s\"\n" "$localBranch" "$remoteName"
    git pull "$remoteName" "$localBranch"
    return 0
  fi

  # Sometimes that isn't possible (e.g. when using branches created via `gh pr
  # checkout`), so let's try something else.
  printf >&2 "No associated remote branch; trying to figure out through config...\n"
  remoteUrl=$(git config --get "branch.$localBranch.remote")
  remoteRef=$(git config --get "branch.$localBranch.merge")
  printf >&2 "Pulling ref \"%s\" from remote \"%s\"\n" "$remoteRef" "$remoteUrl"
  git pull "$remoteUrl" "$remoteRef"
}

gitDir=$(upfind .git)
cd "$gitDir"

case "$1" in
  restore-file)
    [ $# = 2 ] || showHelp
    restoreFile "$2"
    ;;

  fz-restore-file)
    [ $# = 1 ] || showHelp
    file=$(git log --pretty=format: --name-only --diff-filter=A | sort -u | fzagnostic)
    restoreFile "$file" | "$EDITOR"
    ;;

  changed-rank)
    # source: https://stackoverflow.com/a/7686616/7448276

    case $# in
      1) count=10 ;;
      2) count=$2 ;;
      *) showHelp ;;
    esac

    if printf "%s\n" "$count" | grep -v '^[0-9]\+$'; then
      printf >&2 "error: count should be exclusively numeric digits (got %s)\n" "$count"
      exit 1
    fi

    git log --pretty=format: --name-only \
      | sort | uniq -c | sort -rg | head -"$count"

    ;;

  pull-cheap)
    [ $# = 1 ] || showHelp
    pullCheap

    ;;

  push-safe)
    [ $# = 1 ] || showHelp
    localBranch=$(git rev-parse --abbrev-ref HEAD)
    remoteBranch=$(git for-each-ref --format='%(upstream:short)' \
      "$(git symbolic-ref -q HEAD)")
    remoteName=${remoteBranch%%/*}

    if [ "$remoteBranch" ]; then
      printf >&2 "Upstream is \"%s\"\n" "$remoteBranch"
      git push
    else
      printf >&2 "No upstream detected for this branch!\n"
      choice=$(git remote | fzagnostic -p "Pick a remote for this branch:")
      git push --set-upstream "$choice" "$localBranch"
    fi
    ;;

  gitk-local)
    git branch -l \
      | sed 's/^* //g; s/^ \+//g; s/ \+$//g' \
      | tr '\n' ' ' \
      | xargs gitk
    ;;

  *) showHelp ;;
esac
