#!/usr/bin/env sh

. "$(uselib std)"

case "$EDITOR" in
  start-emacs) exec start-emacs "$@" ;;
  emacs) exec emacs -- "$@" ;;
  vi|vim|nvim) exec "$TERMINAL" -e "$EDITOR" -- "$@" ;;
  *) exec "$EDITOR" "$@" ;;
esac
