#!/usr/bin/env sh

. "$(uselib std)"

case "$EDITOR" in
  emacs-custom) exec emacs-custom "$@" ;;
  emacs) exec emacs -- "$@" ;;
  vi|vim|nvim) exec "$TERMINAL" -e "$EDITOR" -- "$@" ;;
  *) exec "$EDITOR" "$@" ;;
esac
