#!/usr/bin/env sh

set -ue
progname=$(basename "$0")

showHelp() {
cat >&2 <<EOF
Usage: $progname <IN> [<OUT>]
EOF
  exit 2
}

if [ ! -e "$1" ]; then
  printf >&2 "file %s doesn't exist...\n" "$1"
  exit 1
fi

# TODO: figure out the resolution

smallMain() {
  if [ -e "$outFile" ]; then
    printf >&2 "output filename %s already exists!\n" "$outFile"
    exit 1
  fi

  magick "$inFile" -resize 40% "$outFile"
}

case $# in
  1)
    noExt=$(printf "%s" "$1" | sd '\.\w+$' '')
    inFile=$1
    outFile="${noExt}_small.jpg"
    smallMain
    ;;
  2)
    inFile=$1
    outFile=$2
    smallMain
    ;;
  *) showHelp ;;
esac
