#!/usr/bin/env bash

set -ue
[ $# = 0 ] || exit 2

{
  find . -maxdepth 1 -type f \
    | grep '\.\(png\|jpg\|jpeg\|svg\|gif\|webp\|apng\)$' \
    | xargs -I{} stat -c"%Y %n" {} \
    | sort -rn \
    | cut -d' ' -f2- \
    | sxiv -t -
} & disown
