#!/usr/bin/env sh

progname=$(basename "$0")
exportStr=''
prefix='#'

filter() {
  gawk -v prefix="$prefix" -v exportStr="$exportStr" '/^base0[a-fA-F0-9]:/ {
    name = gensub(/^(base0[a-fA-F0-9]):$/, "\\1", "g", $1)
    value = gensub(/^"([a-fA-F0-9]{6})"$/, "\\1", "g", $2)
    print sprintf("%s%s=\"%s%s\"", exportStr, name, prefix, value)
  }'
}

showHelp() {
  cat >&2 <<EOF
Usage: $progname [-h | --help] [-e | --export] [ -n | --noprefix ] [THEME]
The theme data is loaded from "\$XDG_CONFIG_HOME/dots/themes/\$THEME.yaml"
EOF
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --export|-e) exportStr='export ' ;;
    --noprefix|-n) prefix='' ;;
    --help|-h) showHelp ;;
    -*)
      printf >&2 "Invalid argument: %s\n" "$1"
      showHelp
      ;;
    *)
      if [ "$themeSpecified" ]; then
        printf >&2 "Repeated THEME argument: %s\n" "$1"
        showHelp
      else
        THEME="$1"
        themeSpecified=1
      fi
      ;;
  esac

  shift
done

case $# in
  0)
    if [ -z "$THEME" ] && [ -f ~/.local/share/dots/theme ]; then
      THEME=$(cat ~/.local/share/dots/theme)
    fi
    if [ -z "$THEME" ]; then
      printf >&2 "Failed to get theme; please set environment variable %s or set the value in ~/.local/share/dots/theme\n" '$THEME'
      exit 1
    fi

    filter <"${XDG_CONFIG_HOME:-$HOME/.config}/dots/themes/${THEME}.yaml"
    ;;
  *) ;;
esac
