#!/usr/bin/env sh

MD_PREVIEW_MODE=1

if [ $# != 1 ]; then
  printf >&2 "%s\n" "Usage: $(basename $0) <file>"
  exit 1
fi

if ! [ -f "$1" ]; then
  printf >&2 "File doesn't exist: %s\n" "$1"
  exit 1
fi

case "$MD_PREVIEW_MODE" in
  0)
    # Delete files from previous runs
    for garbage in /tmp/md-export.*.html; do
      [ -f "$garbage" ] && rm "$garbage"
    done

    TEMP=$(mktemp)
    FILE="/tmp/md-export$(printf "%s" "$TEMP" | sed 's/\///g; s/tmp//g').html"
    mv "$TEMP" "$FILE"
    ;;

  1)
    MDEXPORTS="$XDG_CACHE_HOME/md-exports"
    DIRNAME="$(dirname "$1")"
    BASENAME="$(basename "$1")"

    # Delete old files stored in $MDEXPORTS
    if [ -e "$MDEXPORTS" ]; then
      while read garbage; do
        [ -e "$garbage" ] && rm "$garbage"
      done < "$MDEXPORTS"
      rm < "$MDEXPORTS"
    fi

    FILE="$(realpath -m "$DIRNAME/.md-export.$BASENAME.html")"
    printf "%s\n" "$FILE" >> "$MDEXPORTS"
    ;;
esac

md-compile "$1" > "$FILE" \
  && printf >&2 "%s\n" "Compiled to: $FILE" \
  && OPEN_GUI=1 openfork "$FILE"
