#!/usr/bin/env sh

set -ue
progname=$(basename "$0")

showHelp() {
  cat >&2 <<EOF
$progname: convert a simple OTP code from stdin into an otpauth:// url

Usage: $progname
EOF
  exit 2
}

[ $# != 0 ] && showHelp || true

key=$(tr -d ' ')
printf "otpauth://totp/dummy?secret=%s\n" "$key"
