#!/usr/bin/env sh

if [ $# != 1 ]; then
  printf >&2 "Usage: %s\n" "$(basename "$0") <project_folder>"
fi

if [ -e "$1" ]; then
  printf >&2 '"%s" already exists\n' "$1"
fi

mkdir -p "$1" && cd "$1" && git init
