#!/usr/bin/env sh

if [ $# != 1 ]; then
  printf >&2 "Usage: %s\n" "$(basename "$0") <script_name>"
  exit 1
fi

script="$DOTFILES/scripts/$1"
"$EDITOR" "$script"

if [ -e "$script" ] && [ ! -x "$script" ]; then
  printf >&2 "script detected: chmod-ing it\n"
  chmod +x "$script"
elif [ ! -e "$script" ]; then
  printf >&2 "script does not exist: aborting\n"
fi
