#!/usr/bin/env sh

BATTERY_PATH="/sys/class/power_supply/BAT0/capacity"
CHARGE_STATE_PATH="/sys/class/power_supply/BAT0/status"
DELAY=15

LEVEL_CRITICAL=5
LEVEL_LOW=20
LEVEL_HIGH=90

die() {
  printf >&2 "%s: %s\n" "$(basename $0)" "$*"
  notify-send -u critical -- "$(basename $0): $*"
  exit 1
}

isCharging() { [ "$(cat $CHARGE_STATE_PATH)" = "Charging" ]; }

warn() {
  local msg="$(printf "%s (%02d%%)\n" "$2" "$level")"
  notify-send -u "$1" -- "Battery Information" "$msg"
}

[ -e "$BATTERY_PATH" ] || die "Battery file doesn't exist"
[ -e "$CHARGE_STATE_PATH" ] || die "Charge state file doesn't exist"

# state can be: critical normal low high
state=normal

# main loop
while :; do
  level=$(cat "$BATTERY_PATH")

  if [ "$state" != high ] && [ "$level" -ge "$LEVEL_HIGH" ]; then
    if isCharging; then
      state=high
      warn low "Battery is almost fully charged!"
    else
      state=normal
    fi
  elif [ "$state" != low ] && [ "$state" != critical ] && [ "$level" -le "$LEVEL_LOW" ]; then
    if isCharging; then
      state=normal
    else
      state=low
      warn critical "Battery is low!"
    fi
  elif [ "$state" != critical ] && [ "$level" -le "$LEVEL_CRITICAL" ]; then
    if isCharging; then
      state=normal
    else
      state=critical
      warn critical "Battery is almost empty!"
    fi
  fi

  sleep "$DELAY"
done
