#!/usr/bin/env bash

if [ $# != 2 ]; then
  printf >&2 "Usage: %s <SRC-EXT> <DST-EXT>\n" "$(basename "$0")"
  printf >&2 "Converts all files in the current directory from SRC-EXT to DST-EXT, using ffmpeg\n"
fi

src_ext="$1"
dst_ext="$2"

src_files=(*."$src_ext")

printf >&2 "Will convert (to %s):\n" "$dst_ext"
for f in "${src_files[@]}"; do
  printf >&2 "  %s\n" "$f"
done

printf >&2 "Confirm? [y/N] "
read -r answer

case "$answer" in
  y|Y)
    for f in "${src_files[@]}"; do
      ffmpeg-convert "$f" "$dst_ext"
    done
    ;;
  n|N)
    exit 1
    ;;
  *)
    printf >&2 "Invalid answer\n"
    exit 1
    ;;
esac
