#!/usr/bin/env sh

PROGNAME=$(basename "$0")

usage() {
  printf >&2 "%s\n" "$PROGNAME: checks for ocurrences of a pattern in
filenames inside a directory and their contents.

Usage: $PROGNAME <pattern> [directory]"
}

case $# in
  1) ;;
  2) cd "$2" || exit 1 ;;
  *) usage; exit 1 ;;
esac

printf >&2 "In filenames:\n"; fd -- "$1"
printf >&2 "In files:\n"; rg -- "$1"
