#!/usr/bin/env sh

. ~/.local/lib/ystd.sh
depCheck rg fd

if [ $# != 2 ]; then
  printf >&2 "%s\n" \
    "$(basename $0): checks for ocurrences of a pattern in filenames inside a
directory and their contents.

Usage: $(basename $0) <directory> <pattern>"
  exit 1
fi

cd "$1"
printf "In filenames:\n"; fd -- "$2"
printf "In files:\n"; rg -- "$2"
