#!/usr/bin/env sh

set -ue
progname=$(basename "$0")

showHelp() {
  cat >&2 <<EOF
Usage: $progname <FILE>
Soundfont can be configured through the MIDI_SOUNDFONT env variable.
EOF
  exit 2
}

[ $# = 1 ] || showHelp

synthCount=$(aconnect -o | grep -cv '^ ')
sf2Path=${MIDI_SOUNDFONT:-/usr/share/soundfonts/default.sf2}

printf >&2 "Press Ctrl-C to stop playing\n"

cleanup() { true; }
trap 'cleanup' INT

if [ "$synthCount" -gt 1 ]; then
  port="128:0"
  printf >&2 "Will connect to a synth (port %s)\n" "$port"

  # FIXME: HELLA WONKY. Can fail easily I think
  # TODO: how to stop all notes after ctrlc-ing???
  aplaymidi -p"$port" "$1"
else
  printf >&2 "Using soundfont: %s\n\n" "$sf2Path"

  cleanup() { kill -9 "$fluidsynth_pid"; }
  fluidsynth -a pulseaudio -m alsa_seq -l -g 0.5 -C 0 -i "$sf2Path" "$1" </dev/null &
  fluidsynth_pid="$!"

  wait "$fluidsynth_pid"
fi
