#!/usr/bin/env bash
#
# pp - the text preprocessor
# Originally by Joe Jenne (GNU GPL v3.0)
# Original available at https://github.com/jhjn/pp
#
# Using bash because of \n issues...

die() {
  echo >&2 "Error: $1"
  echo >&2 "Usage: ${0##*/} v0.3.0"
  echo >&2 "  * ${0##*/} < input > output"
  echo >&2 "Syntax:"
  echo >&2 "  * Evaluate lines beginning with \$PP_PREFIX as sh commands"
  echo >&2 "  * Variable \$line contains the line itself"
  echo >&2 "Options:"
  echo >&2 "  * \$PP_PREFIX: the prefix to use (default: !!)"
  exit 1
}

process() {
  PP_PREFIX=${PP_PREFIX:-"!!"}
  while IFS= read -r line; do ln=$((ln+1))
    case $line in
      "$PP_PREFIX"*) eval "${line##"$PP_PREFIX"}" || die "(line $ln): error" ;;
      *) echo "$line" ;;
    esac
  done < "$1"
}

[ $# -ne 0 ] && die "No arguments are taken"
[ -t 0 ] && die "Input text must be provided via stdin"
process "/dev/stdin"
