#!/usr/bin/env python3

import sys

def show_help():
    print("Usage: pyhelp <VALUE>")
    sys.exit(2)

def main(args: list[str]) -> None:
    if len(args) != 2:
        show_help()

    ls = args[1].split(".")
    raise NotImplementedError("TODO: recursively try and access/import till the end")

    help(__import__(args[1]))

if __name__ == "__main__":
    main(sys.argv)
