#!/usr/bin/env bash
#
# A wrapper for reading user input, without choices.
# Uses bash's readline on terminals, and fzagnostic elsewhere.

exists() { command -v "$1" >/dev/null 2>/dev/null; }

while getopts "p:" o; do
  case "$o" in
    p) hasPrompt=1 prompt="$OPTARG" ;;
    *)
      printf >&2 "%s\n" "Usage: $(basename "$0") [-p PROMPT]"
      exit 1
      ;;
  esac
done

if [ ! -t 2 ] && exists fzagnostic; then
  args=()
  [ "$hasPrompt" ] && args+=(-p "$prompt")
  true | fzagnostic "${args[@]}"
elif [ -t 2 ]; then
  [ "$hasPrompt" ] && printf >&2 "%s" "$prompt"
  read -r var
  printf "%s\n" "$var"
else
  printf >&2 "%s\n" "Could not read line."
  exit 1
fi
