#!/usr/bin/env bash
#
# A wrapper for reading user input, without choices.

. "$(uselib std)"

while getopts "p:" o; do
  case "$o" in
    p) hasPrompt=1 prompt="$OPTARG" ;;
    *)
      printf >&2 "%s\n" "Usage: $(basename $0) [-p PROMPT]"
      exit 1
      ;;
  esac
done

if [ ! -t 2 ] && exists dmenu; then
  args=()
  [ "$hasPrompt" ] && args+=(-p "$prompt")
  dmenu "${args[@]}"
elif [ -t 2 ]; then
  [ "$hasPrompt" ] && printf >&2 "%s" "$prompt"
  read var
  printf "%s\n" "$var"
else
  printf >&2 "%s\n" "Could not read line."
  exit 1
fi
