#!/usr/bin/env sh

# a script that runs debug actions based on the specified filetype
# intented for editors like vim and emacs

. "$(uselib std)"

if [ $# != 3 ]; then
  printf >&2 "Usage: %s\n" "$(basename $0) <ACTION> <FILETYPE> <FILENAME>"
  printf >&2 "The ACTION and FILETYPE fields are handled based on the code of this script.\n"
  exit 1
fi

tmp=$(mktemp) || {
  printf >&2 "Could not generate temp file.\n"
  exit 1
}

if [ -z "$3" ]; then
  printf >&2 "Empty filename.\n"
  exit 1
else
  file=$(realpath -m "$3") || exit 1
fi

printf >&2 "@[TEMP: %s]\n\n" "$tmp"
rm -f "$tmp" # remove temp file for preventing any errors related to "file already exists"

cleanup() {
  [ -f "$tmp" ] && rm "$tmp"
  [ -d "$tmp" ] && rm -r "$tmp"
  return 0
}

die() {
  printf >&2 "$@"
  cleanup
  exit 1
}

getModelineCommand() {
  # USAGE: feed this with the file contents.
  modeline=$(head -n1)
  if printf "%s" "$modeline" | grep -q '^#!.*'; then
    printf "%s" "$modeline" | sed 's/^#!//g'
  fi
}

readModeline() { head -n1; }

getPython() {
  if exists python3; then
    echo "python3"
  elif exists python2; then
    echo "python2"
  elif exists python; then
    echo "python"
  elif exists py; then
    echo "py"
  else
    die "Could not find a suitable python version\n"
  fi
}

case "$1" in
  run)
    case "$2" in
      @make) fparent-run "Makefile" run-command file-dir make run ;;
      @cargo) fparent-run "Cargo.toml" run-command file-dir cargo run ;;
      @gradlew) fparent-run "gradlew" run-file script-dir run ;;
      rust) rustc "$file" -o "$tmp" && "$tmp" ;;
      haskell)
        nameFull=${file%.*}
        name=$(basename "$nameFull")
        ghc -o "$tmp" -dynamic "$file" \
          && rm "$nameFull.o" "$nameFull.hi" \
          && "$tmp"
        ;;
      c) gcc "$file" -o "$tmp" && "$tmp" ;;
      cpp|cc) g++ "$file" -o "$tmp" -std=c++20 && "$tmp" ;;
      cs|csharp) mcs "$file" -out:"$tmp" && mono "$tmp" ;;
      clojure) clojure "$file" ;;
      markdown) md-preview "$file" ;;
      sh)
        if [ -x "$file" ]; then
          # execute file if it is executable
          "$file"
        else
          # deduce modeline, if any
          command=$(getModelineCommand < "$file")
          if printf "%s" "$command" | grep -q 'bash$'; then
            bash "$file"
          elif printf "%s" "$command" | grep -q 'zsh$'; then
            zsh "$file"
          elif printf "%s" "$command" | grep -q 'fish$'; then
            fish "$file"
          else
            sh "$file"
          fi
        fi
        ;;
      zsh) if [ -x "$file" ]; then "$file"; else zsh "$file"; fi ;;
      julia) julia "$file" ;;
      vim) nvim -u "$file" ;;
      scheme) guile "$file" ;;
      latex|tex)
        name=$(basename "${file%.*}") \
          && mkdir -p "$tmp" \
          && pdflatex -output-directory "$tmp" "$file" \
          && OPEN_GUI=1 open "$tmp/$name.pdf"
        ;;
      python)
        python=$(getPython)
        "$python" "$file"
        ;;
      hy) hy "$file" ;;
      fsharp) fsharpi "$file" ;;
      lua) lua "$file" ;;
      nim)
        mkdir -p "$tmp" \
          && nim compile --out:"out" --outdir:"$tmp" "$file" \
          && "$tmp/out"
        ;;
      ruby) ruby "$file" ;;
      racket) racket "$file" ;;
      html) openfork "$file" ;;
      moon) moon "$file" ;;
      zig) zig run "$file" ;;
      *) die "(action '%s') unhandled filetype: %s\n" "$1" "$2" ;;
    esac ;;
  build)
    case "$2" in
      @make) fparent-run "Makefile" run-command file-dir make ;;
      @cargo) fparent-run "Cargo.toml" run-command file-dir cargo build ;;
      @gradlew) fparent-run "gradlew" run-file script-dir build ;;
      markdown) md-compile "$file" > "$HOME/$(basename "$file").$(date +%Y-%m-%d).html" ;;
      *) die "(action '%s') unhandled filetype: %s\n" "$1" "$2" ;;
    esac ;;
  test)
    case "$2" in
      @make) fparent-run "Makefile" run-command file-dir make test ;;
      @cargo) fparent-run "Cargo.toml" run-command file-dir cargo test ;;
      *) die "(action '%s') unhandled filetype: %s\n" "$1" "$2" ;;
    esac ;;
  check)
    case "$2" in
      @make) fparent-run "Makefile" run-command file-dir make check ;;
      @cargo) fparent-run "Cargo.toml" run-command file-dir cargo check ;;
      rust) rustc "$file" -o "$tmp" ;;
      nim)
        mkdir -p "$tmp" \
          && nim compile --out:"out" --outdir:"$tmp" "$file"
        ;;
      python)
        python=$(getPython)
        "$python" -m pylint "$file"
        ;;
    esac ;;
  *) die "Invalid action: %s\n" "$1" ;;
esac

cleanup
