#!/usr/bin/env bash

showHelp() {
  cat >&2 <<EOF
$(basename $0): a program to recursively search and run an executable
script from parent directories.

Usage: $(basename $0) <mode> <cmd...>

Where <mode> is:
  0, if <cmd> is a script to be found and it should be ran at current
  directory;
  1, if <cmd> is a script to be found and it should be ran at its
  directory; and
  2, if <cmd> is a file to be found, but arg1 is a command to be ran at
  <cmd>'s directory and arg2+ are the arguments.
EOF

  exit 1
}

filePath="$PWD"
mode="$1"

[ $# -lt 2 ] && showHelp

case "$mode" in
  0|1|2) ;;
  *) showHelp ;;
esac

while true; do
  file="$filePath/$2"

  if [ -f "$file" ]; then
    if [ "$mode" = 2 ]; then
      break
    else
      [ -x "$file" ] && break
    fi
  fi

  [ "$filePath" = "/" ] && exit 1
  filePath=$(realpath -m "$filePath/..")
done

case "$mode" in
  0) "$file" ${@:3} ;;

  1) cd "$filePath"
    "$file" ${@:3} ;;

  2) cmd="$3"
    cd "$filePath"
    "$cmd" ${@:4} ;;
esac
