#!/usr/bin/env sh

# Runs a command silently, but sends a notification with the stderr if
# the exit code is not 0.

. ~/.local/lib/ystd.sh
depCheck notify-send

commandStderr="$("$@" 2>&1 >/dev/null)"
exitCode="$?"

if [ "$exitCode" != 0 ]; then
  # Exit silently if there is no error message and RUNNSEND_STRICT is
  # not set.
  if [ -z "$commandStderr" ] && [ -z "$RUNNSEND_STRICT" ]; then
    exit "$exitCode"
  fi

  headingMessage="$(printf 'Error while running # [%s] %s' "$exitCode" "$*")"
  notify-send "$headingMessage" "$commandStderr"
  exit "$exitCode"
fi
