#!/usr/bin/env sh

# Normalizes the terminal window window with stty sane and then runs a
# command. Sometimes there is a problem with opening vim, and I guess
# this might help.

. ~/.local/lib/ystd.sh

if [ $# = 0 ]; then
  printf >&2 "%s\n" "Usage: $(basename $0) <command> [command]"
  exit 1
fi

stty sane \
  && setTitle "$1" \
  && "$@"
