#!/usr/bin/env sh

if [ $# != 0 ]; then
  printf >&2 "Usage: %s\n" "$(basename $0)"
  printf >&2 "Control is done via the following environment variables:\n"
  printf >&2 " %s : %s\n" "SETBG_IMG_DIR" "The directory where the wallpapers are located (if image)"
  printf >&2 " %s : %s\n" "SETBG_WALLPAPER_TYPE" "The type of background to be set."
  printf >&2 "    -> %s\n" "color -> use hsetroot to set background to 'root.background' resource"
  printf >&2 "    -> %s\n" "{ image | img } -> set background image (see SETBG_IMG_DIR)"
  exit 1
fi

case "$SETBG_WALLPAPER_TYPE" in
  image|img)
    if [ -z "$SETBG_IMG_DIR" ] && [ -f ~/.local/share/dots/wallpath ]; then
        SETBG_IMG_DIR=$(cat ~/.local/share/dots/wallpath)
    fi

    if [ -z "$SETBG_IMG_DIR" ]; then
      printf >&2 "Please set %s to the wallpapers folder path, or leave the value at ~/.local/share/dots/wallpath\n" '$SETBG_IMG_DIR'
      exit 1
    fi

    if [ ! -d "$SETBG_IMG_DIR" ]; then
      printf >&2 "Image dir %s doesn't exist.\n" "$SETBG_IMG_DIR"
      exit 1
    fi

    image=$(shuf -n1 -e "$SETBG_IMG_DIR"/*) || exit 1
    hsetroot -cover "$image" || exit 1
    ;;
  color)
    xresource="root.background"
    color=$(xgetres "$xresource") || {
      printf >&2 "Could not get X resource '%s'\n" "$xresource"
      exit 1
    }
    hsetroot -solid "$color" -brightness -0.05
    ;;
  *)
    printf >&2 "Invalid wallpaper type: %s\n" "$SETBG_WALLPAPER_TYPE"
    exit 1
    ;;
esac



