#!/usr/bin/env sh

if [ $# != 0 ]; then
  printf >&2 "%s\n" "Usage: $(basename $0)"
  exit 1
fi

if [ -z "$SETBG_WALLPAPER_DIR" ]; then
  printf >&2 "Please set %s to the wallpapers folder path\n" '$SETBG_WALLPAPER_DIR'
  exit 1
fi

image="$(shuf -n1 -e "$SETBG_WALLPAPER_DIR"/*.jpg)"
feh --no-fehbg --bg-fill "$image"
