#!/usr/bin/env sh

(
  set -e

  printf >&2 "Commiting on personal repos (via std-commits)...\n"
  std-commits

  # printf >&2 "Regenerating wiki cache...\n"
  # acr-list-titles >/dev/null

  printf >&2 "Tidying up filehist...\n"
  filehist tidy

  printf >&2 "Shutting down soon! 3 seconds...\n"
  sleep 3
  exec systemctl poweroff
)

if test $? != 0; then
  printf >&2 "Press enter to exit... "
  read _
fi
