#!/usr/bin/env sh
#
# A script to launch emacs on different occasions.

if [ -t 1 ] && [ -t 2 ]; then
  onGui=0
else
  onGui=1
fi

launchClient() {
  if [ "$onGui" = 0 ]; then
    TERM=xterm-16color exec emacsclient -a "" -t "$@"
  else
    TERM=xterm-16color exec termup runsane emacsclient -a "" -t "$@"
    # exec emacsclient -a "" -c "$@"
  fi
}

launchStandalone() {
  if [ "$onGui" = 0 ]; then
    TERM=xterm-16color exec emacs -nw "$@"
  else
    # TERM=xterm-16color exec emacs "$@"
    TERM=xterm-16color exec termup runsane emacs -nw "$@"
  fi
}

if [ "$DISPLAY" ]; then
  launchClient "$@"
else
  # launchClient "$@"
  launchStandalone "$@"
fi
