#!/usr/bin/env sh

# starts an X server
# TODO: add support for Xephyr

. "$(uselib std)"
depCheck startx

case $# in
  0) initrc="${XDG_CONFIG_HOME:-$HOME/.config}/xorg/initrc" ;;
  1) initrc="$1" ;;
  2)
    printf >&2 "%s: invalid amount of argument\n" "$(basename $0)"
    printf >&2 "Usage: %s\n" "$(basename $0) [INITRC]"
    printf >&2 "INITRC defaults to %s if not specified.\n" '$XDG_CONFIG_HOME/xorg/initrc'
    exit 1
    ;;
esac

if [ ! -f "$initrc" ] || [ ! -r "$initrc" ]; then
  printf >&2 "Could not open init file %s\n" "$initrc"
  exit 1
fi

if [ "$DISPLAY" ]; then
  printf >&2 "%s is set, an X server is probably already running; aborting\n" '$DISPLAY'
  exit 1
fi

# generate config
gen-config || exit 1

# get tty numbers
stty=$(stty -g)
tty=$(tty)
tty=${tty#/dev/tty} # TODO: handle /dev/pty

export XSESSIONDIR=/tmp/xsessions/$tty
[ -d "$XSESSIONDIR" ] && rm -r "$XSESSIONDIR"
mkdir -p "$XSESSIONDIR"

printf >&2 "Starting at %s\n" "$(date +"%Y/%m/%d %H:%M:%S")"
printf >&2 "Using display ID %s\n" ":$tty"

startx "$initrc" -- :"$tty" -ardelay "${XORG_KBRATE_DELAY:-175}" -arinterval "${XORG_KBRATE_INTERVAL:-37}" >"$XSESSIONDIR/xlog" 2>&1
exitCode="$?"

printf >&2 "Finished at %s\n" "$(date +"%Y/%m/%d %H:%M:%S")"
printf >&2 "Exit code: %s\n" "$exitCode"
exit "$exitCode"
