#!/usr/bin/env sh

set -ue

# TODO: don't kill compositors from other X servers
pgrep "$X_COMPOSITOR" >/dev/null 2>/dev/null \
  && pkill "$X_COMPOSITOR"

while pgrep "$X_COMPOSITOR" >/dev/null 2>/dev/null; do
  sleep 1
done

exec "$X_COMPOSITOR"
