#!/usr/bin/env sh


COMPOSITOR=picom

# TODO: don't kill compositors from other X servers
pgrep "$COMPOSITOR" >/dev/null 2>/dev/null \
  && pkill "$COMPOSITOR"

while pgrep "$COMPOSITOR" >/dev/null 2>/dev/null; do
  sleep 1
done

exec "$COMPOSITOR" --experimental-backend
