#!/usr/bin/env sh
#
# A script to launch emacs on different occasions.

# isGUI() { [ -t 1 ] && [ -t 2 ]; }
isGUI() { true; }

export TERM=xterm-16color

launchClient() {
  if isGUI; then
    exec emacsclient -a "" -t "$@"
  else
    exec d.trun runsane emacsclient -a "" -t "$@"
    # exec emacsclient -a "" -c "$@"
  fi
}

launchStandalone() {
  if isGUI; then
    exec emacs -nw "$@"
  else
    # TERM=xterm-16color exec emacs "$@"
    exec d.trun runsane emacs -nw "$@"
  fi
}

if [ "$DISPLAY" ] || [ "$WAYLAND_DISPLAY" ]; then
  launchClient "$@"
else
  launchStandalone "$@"
fi
