#!/usr/bin/env sh

matches() { printf "%s" "$1" | grep -q "$2"; }
exists() { command -v "$1" >/dev/null; }

if ! exists jq; then
  printf >&2 "JQ NOT AVAILABLE - CAN'T PARSE PINENTRY_USER_DATA\n"
  exit 1
fi

context=$(echo "$PINENTRY_USER_DATA" | jq -r '.context')

export DOTCFG_SOCKET=$(echo "$PINENTRY_USER_DATA" | jq -r '.dotcfg_socket')

if [ "$context" = tty ]; then
  exec pinentry-curses "$@"
else
  if exists pinentry-bemenu; then
    export BEMENU_OPTS="-l 20 $(bemenu-load-colorscheme)"
    exec pinentry-bemenu "$@"
  fi

  for backend in qt gtk-2; do
    prg="pinentry-$backend"
    exists "$prg" && exec "$prg" "$@"
  done

  printf >&2 "COULD NOT FIND SUITABLE PINENTRY\n"
  exit 1
fi
