#!/usr/bin/env sh

COMPOSITOR=picom

pgrep "$COMPOSITOR" >/dev/null 2>/dev/null \
  && pkill "$COMPOSITOR"

while pgrep "$COMPOSITOR" >/dev/null 2>/dev/null; do
  sleep 1
done

"$COMPOSITOR" --experimental-backend
