#!/usr/bin/env sh
#
# A script to start up polybar.

# Terminate already running polybar instances and wait until all the processes
# have been shut down
killall -q polybar
while pgrep -u $(id -ru) -x polybar >/dev/null; do
  sleep 1
done

# find the config path
if [ "$DOTFILES" ]; then
  configPath="$DOTFILES/config/polybar/config.ini"
else
  configPath="${XDG_CONFIG_HOME:-$HOME/.config}/polybar/config.ini"
fi

eval $(load-base16-theme --export)

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  tempLog="$XSESSIONDIR/polybar-$m"
  export POLYBAR_FONT="$(xgetres polybar.fontname):size=$(xgetres polybar.fontsize);2"
  MONITOR=$m polybar --reload main -c "$configPath" >"$tempLog" 2>"$tempLog" &
done
