#!/usr/bin/env bash

# A script to load sxhkd based off the gen-sxhkd script.

. "$(uselib std)"
depCheck gen-sxhkd sxhkd mktemp

. ~/.config/dots/env.sh
. ~/.config/dots/path.sh

# get data folder based on current display
dataFolder="$XSESSIONDIR/sxhkd"
tempConf="$dataFolder/conf"
tempLog="$dataFolder/log"

# cleanup / kill current sxhkd on this display if it exists
if [ -d "$dataFolder" ]; then
  if [ -f "$dataFolder/pid" ]; then
    oldPid="$(cat "$dataFolder/pid")"
    kill "$oldPid" 2>/dev/null
  fi
  rm -r "$dataFolder"
elif [ -f "$dataFolder" ]; then
  rm "$dataFolder"
fi
mkdir -p "$dataFolder"

# generate sxhkd config with gen-sxhkd
gen-sxhkd "$@" > "$tempConf" || {
  printf >&2 "gen-sxhkd failed; aborting\n"
  test -f "$tempConf" && rm "$tempConf"
  exit 1
}

log="$dataFolder/log"

pgrep swhks >/dev/null || { swhks & }
pkexec swhkd -c "$tempConf" 2>"$log" &
pid="$!"

echo "$pid" > "$dataFolder/pid"
wait "$pid" # wait for it to close
