#!/usr/bin/env sh

# A script to load sxhkd based off the gen-sxhkd script.

source ~/.local/lib/ystd.sh
depCheck gen-sxhkd sxhkd mktemp

# get data folder based on current display
dataFolder="/tmp/sxhkd.${DISPLAY}"
tempConf="$dataFolder/conf"
tempLog="$dataFolder/log"

# cleanup / kill current sxhkd on this display if it exists
if [ -r "$dataFolder" ]; then
  if [ -f "$dataFolder/pid" ]; then
    oldPid="$(cat "$dataFolder/pid")"
    ps -C >/dev/null "$oldPid" && kill "$oldPid"
  fi
  rm -r "$dataFolder"
elif [ -f "$dataFolder" ]; then
  rm "$dataFolder"
fi
mkdir "$dataFolder"

# generate sxhkd config with gen-sxhkd
gen-sxhkd "$@" > "$tempConf" || {
  printf >&2 "gen-sxhkd failed; aborting\n"
  test -f "$tempConf" && rm "$tempConf"
  exit 1
}

# start sxhkd and get its pid
sxhkd -c "$tempConf" -r "$tempLog" &
pid="$!"
echo "$pid" > "$dataFolder/pid"

wait "$pid" # wait for sxhkd to close
