#!/usr/bin/env sh

# A simple script to sync some things from my USB station (local to actual USB)
# I still have to explain this.

source ~/.local/lib/ystd.sh
depCheck rsync fd

if [ -z "$F_USB_STATION" ]; then
  printf >&2 "%s\n" 'Variable \$F_USB_STATION not found'
  exit 1
elif [ -z "$DOTFILES" ]; then
  printf >&2 "%s\n" 'Variable \$DOTFILES not found'
  exit 1
fi

mkdir -p "$F_USB_STATION/config/nvim"
rsync -rtuvc --delete "$DOTFILES/config/nvim/" \
  "$F_USB_STATION/config/nvim"

if rsync -rtuvc --delete "$HOME/.cache/nvim-plugs/" \
  "$F_USB_STATION/config/nvim/bundle" \
  && [ -n "$USB_STATION_REMOVE_GIT" ]
then
  fd . "$F_USB_STATION/config/nvim/bundle" -t d -d 1 \
    | while read plugin; do
      for file in .git .gitignore .github; do
        if [ -r "$plugin/$file" ]; then
          rm -rf "$plugin/$file"
        fi
      done
    done
fi
