#!/usr/bin/env sh

source ~/.local/lib/ystd.sh

if exists nvim; then
  alias editor=nvim
elif exists vim; then
  alias editor=vim
else
  echo "Neither vim nor neovim were found."
  exit 1
fi

case $# in
  0) cat /dev/stdin | col -b | editor -c "PagerMode" - ;;
  1) cat "$1" | col -b | editor -c "PagerMode" - ;;
  2) cat "$1" | col -b | editor -c "PagerMode $2" - ;;
  *) echo "Invalid number of arguments." ;;
esac
