#!/usr/bin/env sh

WIKI_DIR="${WIKI:-$HOME/wiki}/vimwiki"

exists() { command -v "$1" >/dev/null 2>/dev/null; }

getNoteTitle() {
  local firstLine

  firstLine=$(head -n1 "$1")

  if printf "%s" "$firstLine" | grep -q '^\s*=\s*.*\s*=\s*$'; then
    printf "%s" "$firstLine" \
      | sed 's|^\s*=\s*\(.*\)\s*=\s*$|\1|' \
      | sed 's| \+$||'
  else
    return 1
  fi
}

exists nvim && alias vim=nvim

case $# in
  0) vim +VimwikiIndex ;;
  1)
    case "$1" in
      browse)
        cd "$wiki_dir"
        choice=$(fd -tf '\.(md|wiki)$' | fzagnostic) || exit 1
        vim "$choice"
        ;;
      list-titles)
        cd "$WIKI_DIR"

        fd -tf '\.wiki$' | while read file; do
          fileWithoutExt=$(printf "%s" "$file" | sed 's|\.wiki$||')
          firstLine=$(getNoteTitle "$file")

          if test $? = 0; then
            printf "%s %s\n" "$fileWithoutExt" "$firstLine"
          else
            printf "%s <No Title>\n" "$fileWithoutExt"
          fi
        done
        ;;
      *) exit 1 ;;
    esac ;;
  2)
    case "$1" in
      open)
        cd "$WIKI_DIR"
        vim "$WIKI_DIR/$2".wiki
        ;;
      *) exit 1 ;;
    esac ;;
  *) exit 1 ;;
esac
