#!/usr/bin/env sh

WIKI_DIR="${WIKI:-$HOME/wiki}/vimwiki"
VIMWIKI_CACHE_DIR="${VIMWIKI_CACHE_DIR:-${XDG_CACHE_DIR:-$HOME/.cache}/vimwiki}"

exists() { command -v "$1" >/dev/null 2>/dev/null; }

getNoteTitle() {
  local firstLine

  firstLine=$(head -n1 "$1")

  if printf "%s" "$firstLine" | grep -q '^\s*=\s*.*\s*=\s*$'; then
    printf "%s" "$firstLine" \
      | sed 's|^\s*=\s*\(.*\)\s*=\s*$|\1|' \
      | sed 's| \+$||'
  else
    return 1
  fi
}

if exists nvim; then
  alias vim=nvim
elif exists vim; then
  true # do nothing
else
  printf >&2 "Could not find a suitable vim-compliant editor - do you have Vim or NeoVim?\n"
fi

case $# in
  0) vim +VimwikiIndex ;;
  1)
    case "$1" in
      browse)
        cd "$WIKI_DIR"
        choice=$(fd -tf '\.(md|wiki)$' | fzagnostic) || exit 1
        vim "$choice"
        ;;
      list-titles)
        # TODO: make this more sophisticated but use C, Zig or something else
        titlegenTimeFile="$VIMWIKI_CACHE_DIR/titlegen-last-time"
        titlegenFile="$VIMWIKI_CACHE_DIR/titlegen"

        mkdir -p "$VIMWIKI_CACHE_DIR"
        if [ -f "$titlegenTimeFile" ]; then
          genLastTime=$(cat "$titlegenTimeFile")
        else
          genLastTime=0
        fi

        wikiLastTime=$(date "+%Y%m%d%H%M%S" -r "$WIKI_DIR")

        if test "$wikiLastTime" -gt "$genLastTime" || ! test -f "$titlegenFile"; then
          cd "$WIKI_DIR"

          fd -tf '\.wiki$' | while read file; do
            fileWithoutExt=$(printf "%s" "$file" | sed 's|\.wiki$||')
            firstLine=$(getNoteTitle "$file")

            if test $? = 0; then
              printf "%s %s\n" "$fileWithoutExt" "$firstLine"
            else
              printf "%s <No Title>\n" "$fileWithoutExt"
            fi
          done | tee "$titlegenFile"

          printf "%s" "$wikiLastTime" >"$titlegenTimeFile"
        else
          cat "$titlegenFile"
        fi
        ;;
      *) exit 1 ;;
    esac ;;
  2)
    case "$1" in
      open)
        cd "$WIKI_DIR"
        vim "$WIKI_DIR/$2".wiki
        ;;
      *) exit 1 ;;
    esac ;;
  *) exit 1 ;;
esac
