#!/usr/bin/env sh

set -ue

WINEW_ARCH="${WINEW_ARCH:-32}" # default arch is 32 bits
WINEW_32_PREFIX="${WINEW_32_PREFIX:-$XDG_DATA_DIR/wine32}"
WINEW_64_PREFIX="${WINEW_64_PREFIX:-$XDG_DATA_DIR/wine64}"
XDG_DATA_DIR="${XDG_DATA_DIR:-$HOME/.local/share}"

progname=$(basename "$0")

exists() { command -v "$1" >/dev/null 2>/dev/null; }
is_x11() { [ "${DISPLAY:-}" ] && [ -z "${WAYLAND_DISPLAY:-}" ]; }

# make sure the wayland version is used on wayland
if [ "${WAYLAND_DISPLAY:-}" ] && [ -z "${NIRI_SOCKET:-}" ]; then
  unset DISPLAY
fi

show_help() {
cat >&2 <<EOF
$progname - dual-prefix wine wrapper/utility

Usage:
  $progname open <PROGRAM> [ARGS...]
    Performs Unix->DOS path conversion on PROGRAM, but not on ARGS.
  $progname cmd
    Open wine's cmd.exe
  $progname cfg
    Open winecfg
  $progname add-recent <BIN>
  $progname tricks <ARGS...>
  $progname server [ARGS...]
  $progname fwd [ARGS...]
    Pass ARGS directly to wine
  $progname fwd-sh [ARGS...]
    Run ARGS directly to the host shell (useful for running a command with the environment set up)
  $progname desktop [ARGS...]
  $progname path [ARGS...]

Used environment variables:
  WINEW_ARCH := { 32 | 64 } (Default: 32)
  WINEW_32_PREFIX: path to the 32-bit wine prefix
  WINEW_64_PREFIX: path to the 64-bit wine prefix
EOF
  exit 2
}

has_line() {
  if [ $# != 1 ]; then
    printf >&2 "%s: invalid amount of arguments\n" "$progname"
    return 1
  fi

  while read -r line; do
    [ "$line" = "$1" ] && return 0
  done

  return 1
}

exec_wine() {
  exec wine "$@"
}

case "$WINEW_ARCH" in
  32) export WINEARCH="win32" WINEPREFIX="$WINEW_32_PREFIX" ;;
  64) export WINEARCH="win64" WINEPREFIX="$WINEW_64_PREFIX" ;;
  *)
    printf >&2 "Unknown arch: %s\n" "$WINEW_ARCH"
    show_help
    ;;
esac

[ $# = 0 ] && show_help

case "$1" in
  cmd)
    [ $# != 1 ] && show_help
    exec_wine cmd
    ;;

  cfg)
    [ $# != 1 ] && show_help
    exec winecfg
    ;;

  desktop)
    [ $# = 0 ] && show_help
    resolution=800x600
    if is_x11 && exists xrandr; then
      resolution=$(xrandr | awk '/\*/ { print $1 }') || resolution=800x600
    fi

    shift
    exec wine explorer /desktop="shell,$resolution" "$@"
    ;;

  fwd)
    shift
    exec_wine "$@"
    exit
    ;;

  fwd-sh)
    shift
    "$@"
    exit
    ;;

  open)
    [ $# -lt 2 ] && show_help
    shift
    program_unix="$1"
    if [ ! -e "$program_unix" ]; then
      printf >&2 "error: program not found: %s\n" "$program_unix"
      exit 1
    fi
    program_dos=$(winepath -w "$program_unix")
    shift
    exec_wine "$program_dos" "$@"
    ;;

  path)
    shift
    exec winepath "$@"
    ;;

  server)
    shift
    exec wineserver "$@"
    ;;

  tricks)
    shift
    exec winetricks "$@"
    ;;

  *)
    printf >&2 "error: unknown command %s\n" "$1"
    show_help
    ;;
esac
