#!/usr/bin/env sh

set -e

tty=$(tty)
if printf "%s" "$tty" | grep -q '^/dev/tty'; then
  tty=${tty#/dev/tty}
elif test "$SX_TTY"; then
  tty=${SX_TTY#/dev/tty}
else
  printf >&2 "%s\n" "Unknown TTY string: '$tty'"
  exit 1
fi

export XSESSIONDIR="/tmp/xsessions/wayland-$tty"

case "$1" in
  river)
    XKB_DEFAULT_LAYOUT="br" river
    ;;
  hyprland)
    hyprland
    ;;
  dwl)
    dwlDir=~/pj/code/dwl-fork
    (cd "$dwlDir" && make) # recompile if needed
    "$dwlDir/dwl"
    ;;
  niri)
    gen-config niri
    niri
    ;;
  qtile)
    qtile start -b wayland
    ;;
  plasma)
    # big ass command...
    /usr/lib/plasma-dbus-run-session-if-needed \
      /usr/bin/startplasma-wayland
    ;;
  *)
    printf >&2 "Unknown Wayland compositor\n"
    exit 1
    ;;
esac
