#!/usr/bin/env sh


tty=$(tty)
if printf "%s" "$tty" | grep -q '^/dev/tty'; then
  tty=${tty#/dev/tty}
elif test "$SX_TTY"; then
  tty=${SX_TTY#/dev/tty}
else
  printf >&2 "%s\n" "Unknown TTY string: '$tty'"
  exit 1
fi

export XSESSIONDIR="/tmp/xsessions/wayland-$tty"

case "$1" in
  river)
    XKB_DEFAULT_LAYOUT="br" river
    ;;
  Hyprland)
    Hyprland
    ;;
  dwl)
    (cd ~/pj/code/dwl-fork && make) && ~/pj/code/dwl-fork/dwl
    ;;
  niri)
    niri
    ;;
  qtile)
    qtile start -b wayland
    ;;
  *)
    printf >&2 "Unknown Wayland compositor\n"
    exit 1
    ;;
esac
