#!/usr/bin/env sh

set -e

tty=$(tty)
if printf "%s" "$tty" | grep -q '^/dev/tty'; then
  tty=${tty#/dev/tty}
elif test "$SX_TTY"; then
  tty=${SX_TTY#/dev/tty}
else
  printf >&2 "%s\n" "Unknown TTY string: '$tty'"
  exit 1
fi

export XSESSIONDIR="/tmp/xsessions/wayland-$tty"

case "$1" in
  river)
    export XKB_DEFAULT_LAYOUT="br"
    exec dbus-launch --exit-with-session river-start
    ;;
  hyprland)
    exec hyprland
    ;;
  dwl)
    dwlDir=~/pj/code/dwl-fork
    (cd "$dwlDir" && make) # recompile if needed
    exec "$dwlDir/dwl"
    ;;
  niri)
    if [ -z "$NIRI_CONFIG" ]; then
      printf >&2 'error: $NIRI_CONFIG not set\n'
      exit 1
    fi
    gen-config niri
    exec niri-session
    ;;
  qtile)
    exec qtile start -b wayland
    ;;
  plasma)
    # big ass command...
    exec /usr/lib/plasma-dbus-run-session-if-needed \
      /usr/bin/startplasma-wayland
    ;;
  gnome)
    export XDG_SESSION_TYPE=wayland
    exec dbus-run-session gnome-session
    ;;
  *)
    printf >&2 "Unknown Wayland compositor: %s\n" "$1"
    exit 1
    ;;
esac
