#!/usr/bin/env sh

PROGNAME=$(basename "$0")

usage() {
  printf >&2 "Usage: %s\n" "$PROGNAME { rl | reload | ed | edit }"
  exit 1
}

main() {
  [ $# != 1 ] && usage

  case "$1" in
    rl|reload) gen-xres | xrdb ;;
    ed|edit)
      progPath=$(which gen-xres) || exit 1

      "$EDITOR" "$progPath" && {
        [ "$DISPLAY" ] && xdb reload
      }
      ;;
    *) usage
  esac
}

main "$@"
