#!/usr/bin/env sh

PROGNAME=$(basename "$0")

usage() {
  printf >&2 "Usage: %s\n" "$PROGNAME"
  exit 1
}

main() {
  [ $# != 0 ] && usage
  [ "$DISPLAY" ] && { gen-res xresources | xrdb; }
  gen-res dotcfg | dotcfg-client read-and-set
  gen-config
}

main "$@"
