#!/usr/bin/env sh

set -e

PROGNAME=$(basename "$0")

usage() {
  printf >&2 "Usage: %s\n" "$PROGNAME"
  exit 1
}

main() {
  [ $# != 0 ] && usage
  [ "$DISPLAY" ] && { gen-res xresources | xrdb; }
  gen-res dotcfg | dotcfg stdin-send >/dev/null
  gen-config
}

main "$@"
